----------------------------
-- JNR 商港拓展适配 by xhh --
----------------------------

-- 建筑本体修改
--------------------------------------------------------------
	-- 基本信息
		-- 商业中心
update Buildings set	PrereqCivic = NULL,				PrereqTech = 'TECH_CURRENCY',					Maintenance = 1,		Cost = 110,	CitizenSlots = 1,	Description = 'LOC_BUILDING_MARKET_DESCRIPTION_UC_JNR'			where BuildingType = 'BUILDING_MARKET';
update Buildings set	PrereqCivic = NULL,				PrereqTech = 'TECH_TEXTILE_HD',				Description = 'LOC_BUILDING_SUKIENNICE_DESCRIPTION_UC_JNR'		where BuildingType = 'BUILDING_SUKIENNICE';
update Buildings set	PrereqCivic = null,				PrereqTech = 'TECH_BANKING',					Maintenance = 4,		Cost = 275,	CitizenSlots = 1,	Description = 'LOC_BUILDING_BANK_DESCRIPTION_UC_JNR'			where BuildingType = 'BUILDING_BANK';
update Buildings set	PrereqCivic = 'CIVIC_GUILDS',	PrereqTech = NULL,								Maintenance = 4,		Cost = 250,	CitizenSlots = 1,	Description = 'LOC_BUILDING_GRAND_BAZAAR_DESCRIPTION_UC_JNR', Entertainment = 2	where BuildingType = 'BUILDING_GRAND_BAZAAR';
update Buildings set	PrereqCivic = NULL,				PrereqTech = 'TECH_ECONOMICS',					Maintenance = 10,		Cost = 450,	CitizenSlots = 1,	Description = 'LOC_BUILDING_STOCK_EXCHANGE_DESCRIPTION_UC_JNR'	where BuildingType = 'BUILDING_STOCK_EXCHANGE';
		-- 港口
update Buildings set	PrereqCivic = NULL,				PrereqTech = 'TECH_CELESTIAL_NAVIGATION',				Maintenance = 1,		Cost = 120,	CitizenSlots = 1,	Description = 'LOC_BUILDING_LIGHTHOUSE_DESCRIPTION_UC_JNR'		where BuildingType = 'BUILDING_LIGHTHOUSE';
update Buildings set	PrereqCivic = NULL,				PrereqTech = 'TECH_MASS_PRODUCTION',			Maintenance = 4,		Cost = 220,	CitizenSlots = 1,	Description = 'LOC_BUILDING_SHIPYARD_DESCRIPTION_UC_JNR'		where BuildingType = 'BUILDING_SHIPYARD';
update Buildings set	PrereqCivic = NULL,				PrereqTech = 'TECH_STEAM_POWER',				Maintenance = 10,		Cost = 400,	CitizenSlots = 1,	Description = 'LOC_BUILDING_SEAPORT_DESCRIPTION_UC_JNR'			where BuildingType = 'BUILDING_SEAPORT';

update Buildings set PrereqTech = 'TECH_HORSEBACK_RIDING' where BuildingType = 'BUILDING_JNR_WAYSTATION';
	-- 数值产出
update Building_YieldChanges set YieldChange = 8 where YieldType = 'YIELD_GOLD' and BuildingType = 'BUILDING_MARKET';
update Building_YieldChanges set YieldChange = 20 where YieldType = 'YIELD_GOLD' and BuildingType = 'BUILDING_BANK';
update Building_YieldChanges set YieldChange = 20 where YieldType = 'YIELD_GOLD' and BuildingType = 'BUILDING_GRAND_BAZAAR';
update Building_YieldChanges set YieldChange = 10 where YieldType = 'YIELD_GOLD' and BuildingType = 'BUILDING_STOCK_EXCHANGE';

update Building_YieldChanges set YieldChange = 2 where YieldType = 'YIELD_FOOD' and BuildingType = 'BUILDING_SHIPYARD';

insert or replace into Building_YieldChanges
	(BuildingType,						YieldType,				YieldChange)
values
	('BUILDING_JNR_MINT',				'YIELD_GOLD',			8),
	('BUILDING_JNR_WAYSTATION',			'YIELD_GOLD',			8),
	('BUILDING_JNR_MERCHANT_QUARTER',	'YIELD_GOLD',			10),
	('BUILDING_JNR_GUILDHALL',			'YIELD_GOLD',			10),
--	('BUILDING_JNR_COMMODITY_EXCHANGE',	'YIELD_GOLD',			8),
	('BUILDING_JNR_MARKETING_AGENCY',	'YIELD_GOLD',			10),
	('BUILDING_JNR_WHARF_FISHING',		'YIELD_FOOD',			1),
	('BUILDING_JNR_WHARF_TRADE',		'YIELD_GOLD',			3),
	('BUILDING_JNR_LIGHTHOUSE_FISHING',				'YIELD_PRODUCTION',		1),
	('BUILDING_LIGHTHOUSE',	'YIELD_GOLD',			3),
	('BUILDING_SHIPYARD',				'YIELD_GOLD',			4),
	('BUILDING_JNR_ENTREPOT',				'YIELD_PRODUCTION',		4),
	('BUILDING_JNR_FISH_MARKET',			'YIELD_GOLD',			8),
	('BUILDING_JNR_OFFSHORE_TERMINAL',	'YIELD_GOLD',			8),
	('BUILDING_JNR_NAVAL_BASE',			'YIELD_PRODUCTION',		4),
	('BUILDING_JNR_NAVAL_BASE',			'YIELD_SCIENCE',		4);

	-- 伟人点产出
insert or replace into Building_GreatPersonPoints
	(BuildingType,							GreatPersonClassType,				PointsPerTurn)
values
	('BUILDING_JNR_MINT',					'GREAT_PERSON_CLASS_MERCHANT',		2),
	('BUILDING_JNR_WAYSTATION',				'GREAT_PERSON_CLASS_MERCHANT',		2),
	('BUILDING_JNR_GUILDHALL',				'GREAT_PERSON_CLASS_MERCHANT',		2),
	-- ('BUILDING_JNR_GUILDHALL',				'GREAT_PERSON_CLASS_ENGINEER',		2),
	('BUILDING_JNR_MERCHANT_QUARTER',		'GREAT_PERSON_CLASS_MERCHANT',		2),
	('BUILDING_JNR_COMMODITY_EXCHANGE',		'GREAT_PERSON_CLASS_MERCHANT',		2),
	('BUILDING_JNR_MARKETING_AGENCY',		'GREAT_PERSON_CLASS_MERCHANT',		2),
	('BUILDING_JNR_LIGHTHOUSE_FISHING',		'GREAT_PERSON_CLASS_ADMIRAL',		2),
	('BUILDING_JNR_ENTREPOT',					'GREAT_PERSON_CLASS_ADMIRAL',		2),
	('BUILDING_JNR_FISH_MARKET',				'GREAT_PERSON_CLASS_ADMIRAL',		2),
	('BUILDING_JNR_OFFSHORE_TERMINAL',		'GREAT_PERSON_CLASS_ADMIRAL',		2),
	('BUILDING_JNR_NAVAL_BASE',				'GREAT_PERSON_CLASS_ADMIRAL',		2);


	-- 通电产出
update Building_YieldChangesBonusWithPower set YieldChange = 10 where BuildingType = 'BUILDING_STOCK_EXCHANGE';

insert or replace into Building_YieldChangesBonusWithPower
	(BuildingType,							YieldType,							YieldChange)
values
	('BUILDING_JNR_MARKETING_AGENCY',		'YIELD_GOLD',						10);

	-- 巨作槽位
delete from Building_GreatWorks where BuildingType = 'BUILDING_STOCK_EXCHANGE';

insert or replace into Building_GreatWorks
	(BuildingType,							GreatWorkSlotType,					NumSlots)
select
	'BUILDING_JNR_COMMODITY_EXCHANGE',		'GREATWORKSLOT_PRODUCT',			2
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into Building_GreatWorks
	(BuildingType,							GreatWorkSlotType,					NumSlots)
select
	'BUILDING_JNR_MARKETING_AGENCY',		'GREATWORKSLOT_PRODUCT',			3
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into Building_GreatWorks
	(BuildingType,							GreatWorkSlotType,					NumSlots)
select
	'BUILDING_JNR_OFFSHORE_TERMINAL',			'GREATWORKSLOT_PRODUCT',			3
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

	-- 专家产出
update Building_CitizenYieldChanges set YieldChange = 2 where YieldType = 'YIELD_GOLD' and BuildingType = 'BUILDING_STOCK_EXCHANGE';

delete from Building_CitizenYieldChanges where BuildingType = 'BUILDING_LIGHTHOUSE';
update Building_CitizenYieldChanges set YieldType = 'YIELD_FOOD' where YieldType = 'YIELD_PRODUCTION' and BuildingType = 'BUILDING_SEAPORT';
update Building_CitizenYieldChanges set YieldChange = -2 where YieldType = 'YIELD_GOLD' and BuildingType = 'BUILDING_SEAPORT';

insert or replace into Building_CitizenYieldChanges
	(BuildingType,							YieldType,							YieldChange)
values
	('BUILDING_JNR_MINT',					'YIELD_GOLD',						2),
	('BUILDING_JNR_WAYSTATION',				'YIELD_GOLD',						2),
	('BUILDING_JNR_GUILDHALL',				'YIELD_GOLD',						2),
	('BUILDING_JNR_MERCHANT_QUARTER',		'YIELD_GOLD',						2),
	('BUILDING_JNR_COMMODITY_EXCHANGE',		'YIELD_GOLD',						2),
	('BUILDING_JNR_MARKETING_AGENCY',		'YIELD_GOLD',						2),
	('BUILDING_JNR_LIGHTHOUSE_FISHING',					'YIELD_FOOD',						1),
	('BUILDING_LIGHTHOUSE',					'YIELD_GOLD',						3),
	('BUILDING_JNR_ENTREPOT',					'YIELD_PRODUCTION',					2),
	('BUILDING_JNR_ENTREPOT',					'YIELD_GOLD',						-2),
	('BUILDING_JNR_FISH_MARKET',				'YIELD_GOLD',						4),
	('BUILDING_JNR_OFFSHORE_TERMINAL',		'YIELD_GOLD',						4),
	('BUILDING_JNR_NAVAL_BASE',				'YIELD_SCIENCE',					1),
	('BUILDING_JNR_NAVAL_BASE',				'YIELD_PRODUCTION',					2),
	('BUILDING_JNR_NAVAL_BASE',				'YIELD_GOLD',						-2);

	-- 辐射范围
update Buildings set RegionalRange = 4 where BuildingType = 'BUILDING_JNR_MINT';
update Buildings set RegionalRange = 6 where BuildingType = 'BUILDING_JNR_GUILDHALL';
update Buildings set RegionalRange = 0 where BuildingType = 'BUILDING_BANK';
update Buildings set RegionalRange = 0 where BuildingType = 'BUILDING_JNR_MERCHANT_QUARTER';
update Buildings set RegionalRange = 0 where BuildingType = 'BUILDING_GRAND_BAZAAR';
--------------------------------------------------------------

-- 建筑特效修改
--------------------------------------------------------------
delete from BuildingModifiers where (ModifierId = 'SHIPYARD_TRAINED_UNIT_XP_MODIFIER' or ModifierId = 'SHIPYARD_NAVAL_UNIT_PRODUCTION') and BuildingType = 'BUILDING_SHIPYARD';
delete from BuildingModifiers where (ModifierId = 'SEAPORT_EXTRA_GREAT_ADMIRAL_POINTS' or ModifierId = 'SEAPORT_TRAINED_STRENGTH_MODIFIER' 
	or ModifierId = 'SEAPORT_TRAINED_UNIT_XP_MODIFIER' or ModifierId = 'SEAPORT_TRAINED_CORPS_ARMY_DISCOUNT') and BuildingType = 'BUILDING_SEAPORT';
delete from BuildingModifiers where ModifierId = 'GRANDBAZAAR_AMENITIES_LUXURIES' and BuildingType = 'BUILDING_GRAND_BAZAAR';

insert or ignore into Types
	(Type,												Kind)
values
	('MODIFIER_SINGLE_CITY_GRANT_TRADING_POST',			'KIND_MODIFIER');

insert or ignore into DynamicModifiers
	(ModifierType,										CollectionType,						EffectType)
values
	('MODIFIER_SINGLE_CITY_GRANT_TRADING_POST',			'COLLECTION_OWNER',					'EFFECT_GRANT_CITY_TRADING_POST');

delete from BuildingModifiers where BuildingType = 'BUILDING_BANK' and ModifierId = 'BANK_GOLD_PERCENTAGE_BOOST';
delete from BuildingModifiers where BuildingType = 'BUILDING_GRAND_BAZAAR' and ModifierId = 'BANK_GOLD_PERCENTAGE_BOOST';

-- 将原本灯塔的效果转给JNR的渔业码头
update BuildingModifiers set BuildingType = 'BUILDING_JNR_LIGHTHOUSE_FISHING' where BuildingType = 'BUILDING_LIGHTHOUSE' and ModifierId != 'HD_AI_BUILDING_LIGHTHOUSE_GREAT_PERSON_CLASS_ADMIRAL';

insert or replace into BuildingModifiers
	(BuildingType,						ModifierId)
values
	-- 市场
	--('BUILDING_MARKET',					'MARKET_CHEAPER_BUILDING_PURCHASE'),
	--('BUILDING_MARKET',					'MARKET_CHEAPER_DISTRICT_PURCHASE'),
	('BUILDING_MARKET',	                    'MARKET_POP_GOLD'),
	-- ('BUILDING_MARKET',					'MARKET_CHEAPER_UNIT_PURCHASE'),
	-- 铸币厂
	('BUILDING_JNR_MINT',				'MARKET_TRADE_ROUTE_CAPACITY'),
	('BUILDING_JNR_MINT',				'MINT_RESOURCE_ADD_GOLD'),
	-- 货栈
	('BUILDING_JNR_WAYSTATION',			'MARKET_TRADE_ROUTE_CAPACITY'),
	('BUILDING_JNR_WAYSTATION',			'WAYSTATION_HORSE_GOLD_ATTACH'),
	('BUILDING_JNR_WAYSTATION',			'WAYSTATION_FREE_TRADING_POSTS'),
--	('BUILDING_JNR_WAYSTATION',			'WAYSTATION_PASTURE_YIELD'),
--	('BUILDING_JNR_WAYSTATION',			'WAYSTATION_CAMP_YIELD'),
	-- ('BUILDING_JNR_WAYSTATION',			'WAYSTATION_FOREIGN_TRADE_PASSING_GOLD'),
	-- ('BUILDING_JNR_WAYSTATION',			'WAYSTATION_GRANT_CITY_TRADING_POST'),
--	('BUILDING_JNR_WAYSTATION',			'WAYSTATION_FREIGHT_INTERNATIONAL_GOLD_ATTACH'),
--	('BUILDING_JNR_WAYSTATION',			'WAYSTATION_FREIGHT_DOMESTIC_FOOD_ATTACH'),
--	('BUILDING_JNR_WAYSTATION',			'WAYSTATION_FREIGHT_DOMESTIC_PRODUCTION_ATTACH'),
	-- 银行
	--('BUILDING_BANK',					'BANK_CHEAPER_BUILDING_PURCHASE'),
	--('BUILDING_BANK',					'BANK_CHEAPER_DISTRICT_PURCHASE'),
	('BUILDING_BANK',	                    'BANK_POP_GOLD'),
	('BUILDING_BANK',			'BANK_EXTRA_GREAT_MERCHANT_POINTS'),
	--('BUILDING_BANK',					'BANK_CHEAPER_UNIT_PURCHASE'),
	-- 会馆
	('BUILDING_JNR_GUILDHALL',			'GUILDHALL_TRADE_GOLD'),
	('BUILDING_JNR_GUILDHALL',			'GUILDHALL_EXTRA_GREAT_ENGINEER_POINTS'),
	--('BUILDING_JNR_GUILDHALL',			'GUILDHALL_TRADE_FOOD'),
	--('BUILDING_JNR_GUILDHALL',			'GUILDHALL_TRADE_PRODUCTION'),
	--('BUILDING_JNR_GUILDHALL',			'GUILDHALL_TRADE_FOOD_INDUSTRIALIZATION'),
	--('BUILDING_JNR_GUILDHALL',			'GUILDHALL_TRADE_PRODUCTION_INDUSTRIALIZATION'),
	-- 商人中心
	('BUILDING_JNR_MERCHANT_QUARTER',	'MERCHANT_QUARTER_TRADE_GOLD'),
	-- ('BUILDING_JNR_MERCHANT_QUARTER',	'BANK_GOLD_PERCENTAGE_BOOST'),
	('BUILDING_JNR_MERCHANT_QUARTER',	'MERCHANT_QUARTER_EXTRA_GREAT_ADMIRAL_POINTS'),
--	('BUILDING_JNR_MERCHANT_QUARTER',	'MERCHANT_QUARTER_TRADE_GOLD_MERCANTILISM'),
	-- 大巴扎
	('BUILDING_GRAND_BAZAAR',	        'BANK_POP_GOLD'),
	('BUILDING_GRAND_BAZAAR',	        'GRAND_BAZAAR_EXTRA_GREAT_MERCHANT_POINTS'),
	-- 交易中心
	-- ('BUILDING_JNR_COMMODITY_EXCHANGE',	'COMMODITY_CHEAPER_BUILDING_PURCHASE'),
	-- ('BUILDING_JNR_COMMODITY_EXCHANGE',	'COMMODITY_CHEAPER_DISTRICT_PURCHASE'),
	-- ('BUILDING_JNR_COMMODITY_EXCHANGE',	'COMMODITY_CHEAPER_UNIT_PURCHASE'),
	('BUILDING_JNR_COMMODITY_EXCHANGE',	'COMMODITY_POWERED_POP_GOLD'),
	-- 市场部
	('BUILDING_JNR_MARKETING_AGENCY',	'MARKETING_TOURISM_BONUS_TRADE'),
	('BUILDING_JNR_MARKETING_AGENCY',	'MARKETING_TOURISM_BONUS_TRADE_POWERED'),
	('BUILDING_JNR_MARKETING_AGENCY',	'MARKETING_GREAT_MERCHANT_POINTS'),
	('BUILDING_JNR_MARKETING_AGENCY',	'MARKETING_COMMERCIAL_ADJACENCY_TOURISM'),
	-- 渔业港市
	('BUILDING_JNR_WHARF_FISHING',		'WHARF_FISHING_ADD_FOOD'),
	('BUILDING_JNR_WHARF_FISHING',		'WHARF_FISHING_ADD_PRODUCTION'),
	-- 贸易港市
	('BUILDING_JNR_WHARF_TRADE',		'WHARF_TRADE_ADD_FOOD'),
	('BUILDING_JNR_WHARF_TRADE',		'WHARF_TRADE_ADD_GOLD'),
	-- 贸易码头
	('BUILDING_LIGHTHOUSE',	'LIGHTHOUSE_TRADE_ROUTE_CAPACITY'),
	('BUILDING_LIGHTHOUSE',	'LIGHTHOUSE_TRAINED_UNIT_XP_MODIFIER'),
	('BUILDING_LIGHTHOUSE',	'TRADE_LIGHTHOUSE_FISHING_BOATS_PRODUCTION'),
	('BUILDING_LIGHTHOUSE',	'TRADE_LIGHTHOUSE_TRADE_GOLD'),
	-- 避风港
	('BUILDING_JNR_ENTREPOT',				'SHIPYARD_TRAINED_UNIT_XP_MODIFIER'),
	('BUILDING_JNR_ENTREPOT',				'SHIPYARD_NAVAL_UNIT_PRODUCTION'),
	('BUILDING_JNR_ENTREPOT',				'HAVEN_NAVAL_UNIT_FREE_PROMOTIONS'),
	('BUILDING_JNR_ENTREPOT',				'HD_DEPOT_ADD_ALUMINUM_RESOURCE_MODIFIER'),
	('BUILDING_JNR_ENTREPOT',				'HD_DEPOT_ADD_COAL_RESOURCE_MODIFIER'),
	('BUILDING_JNR_ENTREPOT',				'HD_DEPOT_ADD_HORSES_RESOURCE_MODIFIER'),
	('BUILDING_JNR_ENTREPOT',				'HD_DEPOT_ADD_IRON_RESOURCE_MODIFIER'),
	('BUILDING_JNR_ENTREPOT',				'HD_DEPOT_ADD_NITER_RESOURCE_MODIFIER'),
	('BUILDING_JNR_ENTREPOT',				'HD_DEPOT_ADD_OIL_RESOURCE_MODIFIER'),
	('BUILDING_JNR_ENTREPOT',				'HD_DEPOT_ADD_URANIUM_RESOURCE_MODIFIER'),
	('BUILDING_JNR_ENTREPOT',				'HAVEN_POP_PRODUCTION'),
	-- 商港
	-- ('BUILDING_JNR_FISH_MARKET',   		'FREEPORT_TRADE_ROUTE_CAPACITY'),
	-- ('BUILDING_JNR_FISH_MARKET',			'FREEPORT_TRADE_SCIENCE'),
	-- ('BUILDING_JNR_FISH_MARKET',			'FREEPORT_TRADE_GOLD'),
	-- ('BUILDING_JNR_FISH_MARKET',			'FREEPORT_TRADE_GOLD_2'),
	('BUILDING_JNR_FISH_MARKET',			'FREEPORT_INTERNATIONAL_TRADE_GOLD'),
	('BUILDING_JNR_FISH_MARKET',			'FREEPORT_DOMESTIC_TRADE_GOLD'),
	-- 海港
	('BUILDING_SEAPORT',				'SEAPORT_IMPROVEMENT_YIELD'),
	('BUILDING_SEAPORT',				'SEAPORT_ENABLE_CORPS_ARMY'),
	-- 游轮码头
	('BUILDING_JNR_OFFSHORE_TERMINAL',	'CRUISE_CITY_APPEAL'),
	('BUILDING_JNR_OFFSHORE_TERMINAL',	'CRUISE_BEACH_TOURISM'),
	('BUILDING_JNR_OFFSHORE_TERMINAL',	'CRUISE_HARBOR_ADJACENCY_TOURISM'),
	('BUILDING_JNR_OFFSHORE_TERMINAL',	'CRUISE_WATERPARK_DOUBLE_TOURISM'),
	('BUILDING_JNR_OFFSHORE_TERMINAL',	'CRUISE_COAST_GOLD'),
	-- 海军基地
	('BUILDING_JNR_NAVAL_BASE',			'SEAPORT_EXTRA_GREAT_ADMIRAL_POINTS'),
	('BUILDING_JNR_NAVAL_BASE',			'SEAPORT_TRAINED_STRENGTH_MODIFIER'),
	('BUILDING_JNR_NAVAL_BASE',			'SEAPORT_TRAINED_UNIT_XP_MODIFIER'),
	('BUILDING_JNR_NAVAL_BASE',			'SEAPORT_TRAINED_CORPS_ARMY_DISCOUNT'),
	('BUILDING_JNR_NAVAL_BASE',			'NAVALBASE_NAVAL_PRODUCTION');

insert or replace into Modifiers
	(ModifierId,									ModifierType,															SubjectRequirementSetId)
values
	-- 市场
	-- ('MARKET_CHEAPER_BUILDING_PURCHASE',			'MODIFIER_SINGLE_CITY_ADJUST_ALL_BUILDINGS_PURCHASE_COST',				NULL),
	-- ('MARKET_CHEAPER_DISTRICT_PURCHASE',			'MODIFIER_SINGLE_CITY_ADJUST_ALL_DISTRICTS_PURCHASE_COST',				NULL),
	-- ('MARKET_CHEAPER_UNIT_PURCHASE',				'MODIFIER_SINGLE_CITY_ADJUST_ALL_UNITS_PURCHASE_COST',					NULL),
	('MARKET_POP_GOLD',				                'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',				NULL),
	-- 铸币厂
	('MINT_RESOURCE_ADD_GOLD',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'HD_PLOT_HAS_COPPER_GOLD_SILVER'),
	-- 货栈
	('WAYSTATION_HORSE_GOLD_ATTACH',				'MODIFIER_CITY_OWNER_ATTACH_MODIFIER',									'PLAYER_HAS_ENOUGH_HORSES_REQUIREMENTS'),
	('WAYSTATION_HORSE_GOLD',						'MODIFIER_SINGLE_CITY_ADJUST_BUILDING_YIELD',							null),
	('WAYSTATION_FREE_TRADING_POSTS',				'MODIFIER_PLAYER_CITIES_GRANT_TRADING_POST',							'CITY_HAS_BUILDING_JNR_WAYSTATION_REQUIREMENTS'),
--	('WAYSTATION_PASTURE_YIELD',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'HD_PLOT_HAS_PASTURE'),
--	('WAYSTATION_CAMP_YIELD',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'PLOT_HAS_CAMP_AND_RESOURCE_REQUIREMENTS'),
--	('WAYSTATION_GRANT_CITY_TRADING_POST',			'MODIFIER_SINGLE_CITY_GRANT_TRADING_POST',								NULL),
--	('WAYSTATION_FREIGHT_INTERNATIONAL_GOLD_ATTACH',	'MODIFIER_CITY_OWNER_ATTACH_MODIFIER',								'CITY_HAS_BUILDING_CITY_POLICY_FREIGHT'),
--	('WAYSTATION_FREIGHT_DOMESTIC_FOOD_ATTACH',			'MODIFIER_CITY_OWNER_ATTACH_MODIFIER',								'CITY_HAS_BUILDING_CITY_POLICY_FREIGHT'),
--	('WAYSTATION_FREIGHT_DOMESTIC_PRODUCTION_ATTACH',	'MODIFIER_CITY_OWNER_ATTACH_MODIFIER',								'CITY_HAS_BUILDING_CITY_POLICY_FREIGHT'),
--	('WAYSTATION_FREIGHT_INTERNATIONAL_GOLD',		'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		null),
--	('WAYSTATION_FREIGHT_DOMESTIC_FOOD',			'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS',				null),
--	('WAYSTATION_FREIGHT_DOMESTIC_PRODUCTION',		'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS',				null),
	-- 纺织会馆
	-- ('SUKIENNICE_LUXURY_YIELD',						'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'HD_PLOT_HAS_RESOURCE_REQUIREMENTS'),
	-- 银行
	--('BANK_CHEAPER_BUILDING_PURCHASE',				'MODIFIER_SINGLE_CITY_ADJUST_ALL_BUILDINGS_PURCHASE_COST',				'PLAYER_HAS_TECH_BANKING_REQUIREMENTS'),
	--('BANK_CHEAPER_DISTRICT_PURCHASE',				'MODIFIER_SINGLE_CITY_ADJUST_ALL_DISTRICTS_PURCHASE_COST',				'PLAYER_HAS_TECH_BANKING_REQUIREMENTS'),
	--('BANK_CHEAPER_UNIT_PURCHASE',					'MODIFIER_SINGLE_CITY_ADJUST_ALL_UNITS_PURCHASE_COST',					'PLAYER_HAS_TECH_BANKING_REQUIREMENTS'),
	('BANK_POP_GOLD',								'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',				NULL),
	('BANK_EXTRA_GREAT_MERCHANT_POINTS',								'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',				NULL),
	-- 会馆
	('GUILDHALL_TRADE_GOLD',						'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS',				NULL),
	('GUILDHALL_EXTRA_GREAT_ENGINEER_POINTS',						'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',				NULL),
	--('GUILDHALL_TRADE_FOOD',						'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',			NULL),
	--('GUILDHALL_TRADE_PRODUCTION',					'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',			NULL),
	--('GUILDHALL_TRADE_FOOD_INDUSTRIALIZATION',		'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS',				'PLAYER_HAS_TECH_INDUSTRIALIZATION_REQUIREMENTS'),
	--('GUILDHALL_TRADE_PRODUCTION_INDUSTRIALIZATION','MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS',				'PLAYER_HAS_TECH_INDUSTRIALIZATION_REQUIREMENTS'),
	-- 大巴扎
	-- ('GRAND_BAZAAR_BONUS_RESOURCE_EXTRA_AMENITIES',	'MODIFIER_PLAYER_OWNED_BONUS_RESOURCE_EXTRA_AMENITIES',					NULL),
	('GRAND_BAZAAR_EXTRA_GREAT_MERCHANT_POINTS',								'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',				NULL),
	-- 商人中心
	('MERCHANT_QUARTER_TRADE_GOLD',					'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		NULL),
	('MERCHANT_QUARTER_EXTRA_GREAT_ADMIRAL_POINTS',					'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',		NULL),
--	('MERCHANT_QUARTER_TRADE_GOLD_MERCANTILISM',	'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		'PLAYER_HAS_CIVIC_MERCANTILISM_REQUIREMENTS'),
	-- 交易中心
	-- ('COMMODITY_CHEAPER_BUILDING_PURCHASE',			'MODIFIER_SINGLE_CITY_ADJUST_ALL_BUILDINGS_PURCHASE_COST',				NULL),
	-- ('COMMODITY_CHEAPER_DISTRICT_PURCHASE',			'MODIFIER_SINGLE_CITY_ADJUST_ALL_DISTRICTS_PURCHASE_COST',				NULL),
	-- ('COMMODITY_CHEAPER_UNIT_PURCHASE',				'MODIFIER_SINGLE_CITY_ADJUST_ALL_UNITS_PURCHASE_COST',					NULL),
	('COMMODITY_POWERED_POP_GOLD',					'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',				'CITY_IS_POWERED'),
	-- 市场部
	('MARKETING_TOURISM_BONUS_TRADE',				'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_TOURISM_MODIFIER',					NULL),
	('MARKETING_TOURISM_BONUS_TRADE_POWERED',		'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_TOURISM_MODIFIER',					NULL),
	('MARKETING_GREAT_MERCHANT_POINTS',				'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',					Null),
	('MARKETING_COMMERCIAL_ADJACENCY_TOURISM',				'MODIFIER_CITY_DISTRICTS_ADJUST_TOURISM_ADJACENCY_YIELD_MOFIFIER',					'DISTRICT_IS_COMMERCIAL_HUB'),
	-- 渔业港市
	('WHARF_FISHING_ADD_FOOD',						'MODIFIER_BUILDING_YIELD_CHANGE',										'HD_WHARF_FISHING_REQUIREMENT'),
	('WHARF_FISHING_ADD_PRODUCTION',				'MODIFIER_BUILDING_YIELD_CHANGE',										'HD_WHARF_FISHING_REQUIREMENT'),
	-- 贸易港市
	('WHARF_TRADE_ADD_FOOD',						'MODIFIER_BUILDING_YIELD_CHANGE',										'HD_WHARF_TRADE_REQUIREMENT'),
	('WHARF_TRADE_ADD_GOLD',						'MODIFIER_BUILDING_YIELD_CHANGE',										'HD_WHARF_TRADE_REQUIREMENT'),
	-- 贸易码头
	('TRADE_LIGHTHOUSE_FISHING_BOATS_PRODUCTION',	'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'PLOT_HAS_FISHINGBOATS_REQUIREMENTS'),
	--('TRADE_LIGHTHOUSE_COAST_LUXURY_PRODUCTION',	'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'HD_PLOT_HAS_COAST_LUXURY_RESOURCE_REQUIREMENTS'),
	--('TRADE_LIGHTHOUSE_SEA_LUXURY_GOLD',			'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'HD_PLOT_HAS_SEA_LUXURY_RESOURCE_REQUIREMENTS'),
	--('TRADE_LIGHTHOUSE_COAST_LUXURY_GOLD',			'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'HD_PLOT_HAS_COAST_LUXURY_RESOURCE_REQUIREMENTS'),
	--('TRADE_LIGHTHOUSE_SEA_BONUS_PRODUCTION',		'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'HD_PLOT_HAS_SEA_BONUS_RESOURCE_REQUIREMENTS'),
	--('TRADE_LIGHTHOUSE_COAST_BONUS_PRODUCTION',		'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'HD_PLOT_HAS_COAST_BONUS_RESOURCE_REQUIREMENTS'),
	('TRADE_LIGHTHOUSE_TRADE_GOLD',					'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		NULL),
	-- 避风港
	('HAVEN_NAVAL_UNIT_FREE_PROMOTIONS',			'MODIFIER_CITY_TRAINED_UNITS_ADJUST_GRANT_EXPERIENCE',					'HD_UNIT_IS_NAVAL'),
	('HAVEN_POP_PRODUCTION',			'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_PER_POPULATION',					NULL),
	-- 商港
	-- ('FREEPORT_TRADE_ROUTE_CAPACITY',   			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',							null),
	-- ('FREEPORT_TRADE_SCIENCE',						'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		NULL),
	-- ('FREEPORT_TRADE_GOLD',							'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		NULL),
	-- ('FREEPORT_TRADE_GOLD_2',						'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',			NULL),
	('FREEPORT_INTERNATIONAL_TRADE_GOLD',		'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',			NULL),
	('FREEPORT_DOMESTIC_TRADE_GOLD',				'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS',			NULL),
	-- 海港
	('SEAPORT_IMPROVEMENT_YIELD',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'HD_PLOT_HAS_FISHERY_OILWELL_WINDPOWER_SEASTEAD'),
	('SEAPORT_ENABLE_CORPS_ARMY',					'MODIFIER_CITY_CORPS_ARMY_ADJUST_DISCOUNT',								NULL),
	-- 游轮码头
	('CRUISE_CITY_APPEAL',							'MODIFIER_SINGLE_CITY_ADJUST_CITY_APPEAL',								NULL),
	('CRUISE_BEACH_TOURISM',						'MODIFIER_SINGLE_CITY_ADJUST_TOURISM',									NULL),
	('CRUISE_HARBOR_ADJACENCY_TOURISM',				'MODIFIER_CITY_DISTRICTS_ADJUST_TOURISM_ADJACENCY_YIELD_MOFIFIER',		'DISTRICT_IS_HARBOR'),
	('CRUISE_WATERPARK_DOUBLE_TOURISM',				'MODIFIER_CITY_DISTRICTS_ADJUST_TOURISM_ADJACENCY_YIELD_MOFIFIER',		'DISTRICT_IS_HARBOR'),
	('CRUISE_COAST_GOLD',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',								'PLOT_HAS_COAST_REQUIREMENTS'),
	-- 海军基地
	('NAVALBASE_NAVAL_PRODUCTION',					'MODIFIER_CITY_ADJUST_UNIT_DOMAIN_PRODUCTION',							NULL);

update Modifiers set SubjectStackLimit = 5 where ModifierId = 'MARKETING_TOURISM_BONUS_TRADE';
update Modifiers set SubjectStackLimit = 5, OwnerRequirementSetId = 'CITY_IS_POWERED' where ModifierId = 'MARKETING_TOURISM_BONUS_TRADE_POWERED';
update Modifiers set OwnerRequirementSetId = 'HD_ADJACENT_TO_ANY_ENTERTAINMENT_COMPLEX' where ModifierId = 'CRUISE_WATERPARK_DOUBLE_TOURISM';
update Modifiers set OwnerRequirementSetId = 'HD_CITY_DISTRICT_COMMERCIAL_HUB_HAS_6_ADJACENCY_REQUIREMENTS' where ModifierId = 'BANK_EXTRA_GREAT_MERCHANT_POINTS';
update Modifiers set OwnerRequirementSetId = 'HD_CITY_DISTRICT_INDUSTRIAL_ZONE_HAS_6_ADJACENCY_REQUIREMENTS' where ModifierId = 'GUILDHALL_EXTRA_GREAT_ENGINEER_POINTS';
update Modifiers set OwnerRequirementSetId = 'HD_CITY_DISTRICT_HARBOR_HAS_6_ADJACENCY_REQUIREMENTS' where ModifierId = 'MERCHANT_QUARTER_EXTRA_GREAT_ADMIRAL_POINTS';

insert or replace into ModifierArguments
	(ModifierId,									Name,						Value)
values
	-- 市场
	-- ('MARKET_CHEAPER_BUILDING_PURCHASE',			'Amount',					5),
	-- ('MARKET_CHEAPER_DISTRICT_PURCHASE',			'Amount',					5),
	-- ('MARKET_CHEAPER_UNIT_PURCHASE',				'Amount',					5),
	-- ('MARKET_CHEAPER_UNIT_PURCHASE',				'IncludeCivilian',			1),
	('MARKET_POP_GOLD',				            	'YieldType',				'YIELD_GOLD'),
	('MARKET_POP_GOLD',					            'Amount',					1),
	-- 铸币厂
	('MINT_RESOURCE_ADD_GOLD',						'YieldType',				'YIELD_GOLD'),
	('MINT_RESOURCE_ADD_GOLD',						'Amount',					3),
	-- 货栈
	('WAYSTATION_HORSE_GOLD_ATTACH',				'ModifierId',				'WAYSTATION_HORSE_GOLD'),
	('WAYSTATION_HORSE_GOLD',						'BuildingType',				'BUILDING_JNR_WAYSTATION'),
	('WAYSTATION_HORSE_GOLD',						'YieldType',				'YIELD_GOLD'),
	('WAYSTATION_HORSE_GOLD',						'Amount',					10),
	--('WAYSTATION_PASTURE_YIELD',					'YieldType',				'YIELD_FOOD'),
	--('WAYSTATION_PASTURE_YIELD',					'Amount',					1),
	--('WAYSTATION_CAMP_YIELD',						'YieldType',				'YIELD_FOOD'),
	--('WAYSTATION_CAMP_YIELD',						'Amount',					1),
	--('WAYSTATION_FREIGHT_INTERNATIONAL_GOLD_ATTACH','ModifierId',				'WAYSTATION_FREIGHT_INTERNATIONAL_GOLD'),
	--('WAYSTATION_FREIGHT_INTERNATIONAL_GOLD',		'YieldType',				'YIELD_GOLD'),
	--('WAYSTATION_FREIGHT_INTERNATIONAL_GOLD',		'Amount',					8),
	--('WAYSTATION_FREIGHT_DOMESTIC_FOOD_ATTACH',		'ModifierId',				'WAYSTATION_FREIGHT_DOMESTIC_FOOD'),
	--('WAYSTATION_FREIGHT_DOMESTIC_FOOD',			'YieldType',				'YIELD_FOOD'),
	--('WAYSTATION_FREIGHT_DOMESTIC_FOOD',			'Amount',					1),
	--('WAYSTATION_FREIGHT_DOMESTIC_FOOD',			'Domestic',					1),
	--('WAYSTATION_FREIGHT_DOMESTIC_PRODUCTION_ATTACH','ModifierId',				'WAYSTATION_FREIGHT_DOMESTIC_PRODUCTION'),
	--('WAYSTATION_FREIGHT_DOMESTIC_PRODUCTION',		'YieldType',				'YIELD_PRODUCTION'),
	--('WAYSTATION_FREIGHT_DOMESTIC_PRODUCTION',		'Amount',					1),
	--('WAYSTATION_FREIGHT_DOMESTIC_PRODUCTION',		'Domestic',					1),
	-- 纺织会馆
	-- ('SUKIENNICE_LUXURY_YIELD',						'YieldType',				'YIELD_PRODUCTION,YIELD_GOLD'),
	-- ('SUKIENNICE_LUXURY_YIELD',						'Amount',					'1,2'),
	-- 银行
	-- ('BANK_CHEAPER_BUILDING_PURCHASE',				'Amount',					15),
	-- ('BANK_CHEAPER_DISTRICT_PURCHASE',				'Amount',					15),
	-- ('BANK_CHEAPER_UNIT_PURCHASE',					'Amount',					15),
	-- ('BANK_CHEAPER_UNIT_PURCHASE',					'IncludeCivilian',			1),
	('BANK_POP_GOLD',				            	'YieldType',				'YIELD_GOLD'),
	('BANK_POP_GOLD',					            'Amount',					3),
	('BANK_EXTRA_GREAT_MERCHANT_POINTS',						'Amount',					10),
	('BANK_EXTRA_GREAT_MERCHANT_POINTS',						'GreatPersonClassType',					'GREAT_PERSON_CLASS_MERCHANT'),
	-- 会馆
	('GUILDHALL_TRADE_GOLD',						'YieldType',				'YIELD_GOLD'),
	('GUILDHALL_TRADE_GOLD',						'Amount',					5),
	('GUILDHALL_TRADE_GOLD',						'Domestic',					1),
	('GUILDHALL_EXTRA_GREAT_ENGINEER_POINTS',						'Amount',					10),
	('GUILDHALL_EXTRA_GREAT_ENGINEER_POINTS',						'GreatPersonClassType',					'GREAT_PERSON_CLASS_ENGINEER'),
	--('GUILDHALL_TRADE_FOOD',						'YieldType',				'YIELD_FOOD'),
	--('GUILDHALL_TRADE_FOOD',						'Amount',					2),
	--('GUILDHALL_TRADE_PRODUCTION',					'YieldType',				'YIELD_PRODUCTION'),
	--('GUILDHALL_TRADE_PRODUCTION',					'Amount',					2),
	--('GUILDHALL_TRADE_FOOD_INDUSTRIALIZATION',		'YieldType',				'YIELD_FOOD'),
	--('GUILDHALL_TRADE_FOOD_INDUSTRIALIZATION',		'Amount',					2),
	--('GUILDHALL_TRADE_FOOD_INDUSTRIALIZATION',		'Domestic',					1),
	--('GUILDHALL_TRADE_PRODUCTION_INDUSTRIALIZATION','YieldType',				'YIELD_PRODUCTION'),
	--('GUILDHALL_TRADE_PRODUCTION_INDUSTRIALIZATION','Amount',					2),
	--('GUILDHALL_TRADE_PRODUCTION_INDUSTRIALIZATION','Domestic',					1),
	-- 大巴扎
	-- ('GRAND_BAZAAR_BONUS_RESOURCE_EXTRA_AMENITIES',	'Amount',					2),
	('GRAND_BAZAAR_EXTRA_GREAT_MERCHANT_POINTS',						'Amount',					10),
	('GRAND_BAZAAR_EXTRA_GREAT_MERCHANT_POINTS',						'GreatPersonClassType',					'GREAT_PERSON_CLASS_MERCHANT'),
	-- 商人中心
	('MERCHANT_QUARTER_TRADE_GOLD',					'YieldType',				'YIELD_GOLD'),
	('MERCHANT_QUARTER_TRADE_GOLD',					'Amount',					6),
	('MERCHANT_QUARTER_EXTRA_GREAT_ADMIRAL_POINTS',						'Amount',					10),
	('MERCHANT_QUARTER_EXTRA_GREAT_ADMIRAL_POINTS',						'GreatPersonClassType',					'GREAT_PERSON_CLASS_ADMIRAL'),
--	('MERCHANT_QUARTER_TRADE_GOLD_MERCANTILISM',	'YieldType',				'YIELD_GOLD'),
--	('MERCHANT_QUARTER_TRADE_GOLD_MERCANTILISM',	'Amount',					5),
	-- 交易中心
	-- ('COMMODITY_CHEAPER_BUILDING_PURCHASE',			'Amount',					10),
	-- ('COMMODITY_CHEAPER_DISTRICT_PURCHASE',			'Amount',					10),
	-- ('COMMODITY_CHEAPER_UNIT_PURCHASE',				'Amount',					10),
	-- ('COMMODITY_CHEAPER_UNIT_PURCHASE',				'IncludeCivilian',			1),
	('COMMODITY_POWERED_POP_GOLD',					'YieldType',				'YIELD_PRODUCTION'),
	('COMMODITY_POWERED_POP_GOLD',					'Amount',					1),
	-- 市场部
	('MARKETING_TOURISM_BONUS_TRADE',				'Amount',					5),
	('MARKETING_TOURISM_BONUS_TRADE_POWERED',		'Amount',					5),
	('MARKETING_GREAT_MERCHANT_POINTS',				'GreatPersonClassType',		'GREAT_PERSON_CLASS_MERCHANT'),
	('MARKETING_GREAT_MERCHANT_POINTS',				'Amount',					10),
	('MARKETING_COMMERCIAL_ADJACENCY_TOURISM',				'YieldType',				'YIELD_GOLD'),
	('MARKETING_COMMERCIAL_ADJACENCY_TOURISM',				'Amount',					100),
	-- 渔业港市
	('WHARF_FISHING_ADD_FOOD',						'BuildingType',				'BUILDING_JNR_WHARF_FISHING'),
	('WHARF_FISHING_ADD_FOOD',						'YieldType',				'YIELD_FOOD'),
	('WHARF_FISHING_ADD_FOOD',						'Amount',					1),
	('WHARF_FISHING_ADD_PRODUCTION',				'BuildingType',				'BUILDING_JNR_WHARF_FISHING'),
	('WHARF_FISHING_ADD_PRODUCTION',				'YieldType',				'YIELD_PRODUCTION'),
	('WHARF_FISHING_ADD_PRODUCTION',				'Amount',					1),
	-- 贸易港市
	('WHARF_TRADE_ADD_FOOD',						'BuildingType',				'BUILDING_JNR_WHARF_TRADE'),
	('WHARF_TRADE_ADD_FOOD',						'YieldType',				'YIELD_FOOD'),
	('WHARF_TRADE_ADD_FOOD',						'Amount',					1),
	('WHARF_TRADE_ADD_GOLD',						'BuildingType',				'BUILDING_JNR_WHARF_TRADE'),
	('WHARF_TRADE_ADD_GOLD',						'YieldType',				'YIELD_GOLD'),
	('WHARF_TRADE_ADD_GOLD',						'Amount',					3),
	-- 贸易码头
	('TRADE_LIGHTHOUSE_FISHING_BOATS_PRODUCTION',	'YieldType',				'YIELD_PRODUCTION'),
	('TRADE_LIGHTHOUSE_FISHING_BOATS_PRODUCTION',	'Amount',					1),
	--('TRADE_LIGHTHOUSE_COAST_LUXURY_PRODUCTION',	'YieldType',				'YIELD_PRODUCTION'),
	--('TRADE_LIGHTHOUSE_COAST_LUXURY_PRODUCTION',	'Amount',					1),
	--('TRADE_LIGHTHOUSE_SEA_LUXURY_GOLD',			'YieldType',				'YIELD_GOLD'),
	--('TRADE_LIGHTHOUSE_SEA_LUXURY_GOLD',			'Amount',					2),
	--('TRADE_LIGHTHOUSE_COAST_LUXURY_GOLD',			'YieldType',				'YIELD_GOLD'),
	--('TRADE_LIGHTHOUSE_COAST_LUXURY_GOLD',			'Amount',					2),
	--('TRADE_LIGHTHOUSE_SEA_BONUS_PRODUCTION',		'YieldType',				'YIELD_PRODUCTION'),
	--('TRADE_LIGHTHOUSE_SEA_BONUS_PRODUCTION',		'Amount',					1),
	--('TRADE_LIGHTHOUSE_COAST_BONUS_PRODUCTION',		'YieldType',				'YIELD_PRODUCTION'),
	--('TRADE_LIGHTHOUSE_COAST_BONUS_PRODUCTION',		'Amount',					1),
	('TRADE_LIGHTHOUSE_TRADE_GOLD',					'YieldType',				'YIELD_GOLD'),
	('TRADE_LIGHTHOUSE_TRADE_GOLD',					'Amount',					2),
	-- 避风港
	('HAVEN_NAVAL_UNIT_FREE_PROMOTIONS',			'Amount',					-1),
	('HAVEN_POP_PRODUCTION',					'YieldType',				'YIELD_PRODUCTION'),
	('HAVEN_POP_PRODUCTION',					'Amount',					1),
	-- 商港
	-- ('FREEPORT_TRADE_ROUTE_CAPACITY',   			'Amount',   				1),
	-- ('FREEPORT_TRADE_SCIENCE',						'YieldType',				'YIELD_SCIENCE'),
	-- ('FREEPORT_TRADE_SCIENCE',						'Amount',					2),
	-- ('FREEPORT_TRADE_GOLD',							'YieldType',				'YIELD_GOLD'),
	-- ('FREEPORT_TRADE_GOLD',							'Amount',					6),
	-- ('FREEPORT_TRADE_GOLD_2',						'YieldType',				'YIELD_GOLD'),
	-- ('FREEPORT_TRADE_GOLD_2',						'Amount',					4),
	('FREEPORT_DOMESTIC_TRADE_GOLD',						'YieldType',				'YIELD_GOLD'),
	('FREEPORT_DOMESTIC_TRADE_GOLD',						'Amount',					6),
	('FREEPORT_DOMESTIC_TRADE_GOLD',						'Domestic',					1),
	('FREEPORT_INTERNATIONAL_TRADE_GOLD',						'YieldType',				'YIELD_GOLD'),
	('FREEPORT_INTERNATIONAL_TRADE_GOLD',						'Amount',					6),
	-- 海港
	('SEAPORT_IMPROVEMENT_YIELD',					'YieldType',				'YIELD_PRODUCTION'),
	('SEAPORT_IMPROVEMENT_YIELD',					'Amount',					2),
	('SEAPORT_ENABLE_CORPS_ARMY',					'UnitDomain',				'DOMAIN_SEA'),
	('SEAPORT_ENABLE_CORPS_ARMY',					'Amount',					10),
	-- 游轮码头
	('CRUISE_CITY_APPEAL',							'Amount',					1),
	('CRUISE_BEACH_TOURISM',						'ImprovementType',			'IMPROVEMENT_BEACH_RESORT'),
	('CRUISE_BEACH_TOURISM',						'ScalingFactor',			150),
	('CRUISE_HARBOR_ADJACENCY_TOURISM',				'YieldType',				'YIELD_GOLD'),
	('CRUISE_HARBOR_ADJACENCY_TOURISM',				'Amount',					100),
	('CRUISE_WATERPARK_DOUBLE_TOURISM',				'YieldType',				'YIELD_GOLD'),
	('CRUISE_WATERPARK_DOUBLE_TOURISM',				'Amount',					100),
	('CRUISE_COAST_GOLD',					'YieldType',			'YIELD_GOLD'),
	('CRUISE_COAST_GOLD',					'Amount',					3),
	-- 海军基地
	('NAVALBASE_NAVAL_PRODUCTION',					'Domain',					'DOMAIN_SEA'),
	('NAVALBASE_NAVAL_PRODUCTION',					'Amount',					75);

update ModifierArguments set Value = 50 where Name = 'Amount' and ModifierId = 'SHIPYARD_NAVAL_UNIT_PRODUCTION';
delete from BuildingModifiers where ModifierId = 'GRANDBAZAAR_ACCUMULATION_STRATEGICS';
update ModifierArguments set Value = 2 where Name = 'Amount' and ModifierId = 'GRANDBAZAAR_ACCUMULATION_STRATEGICS';

insert or ignore into RequirementSets
	(RequirementSetId,										RequirementSetType)
values
	-- 铸币厂
	('HD_PLOT_HAS_COPPER_GOLD_SILVER',						'REQUIREMENTSET_TEST_ANY'),
	-- 货栈
	-- 会馆
	('CITY_HAS_BUILDING_WORKSHOP',							'REQUIREMENTSET_TEST_ALL'),
	-- 贸易码头
	('HD_PLOT_HAS_SEA_LUXURY_RESOURCE_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL'),
	('HD_PLOT_HAS_COAST_LUXURY_RESOURCE_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL'),
	('HD_PLOT_HAS_SEA_BONUS_RESOURCE_REQUIREMENTS',			'REQUIREMENTSET_TEST_ALL'),
	('HD_PLOT_HAS_COAST_BONUS_RESOURCE_REQUIREMENTS',		'REQUIREMENTSET_TEST_ALL'),
	-- 避风港
	--('HD_UNIT_IS_NAVAL',									'REQUIREMENTSET_TEST_ALL'),
	-- 海港
	('HD_PLOT_HAS_FISHERY_OILWELL_WINDPOWER_SEASTEAD',		'REQUIREMENTSET_TEST_ANY'),
	-- 游轮码头
	('HD_ADJACENT_TO_ANY_ENTERTAINMENT_COMPLEX',			'REQUIREMENTSET_TEST_ANY');

insert or ignore into RequirementSetRequirements
	(RequirementSetId,										RequirementId)
values
	-- 铸币厂
	('HD_PLOT_HAS_COPPER_GOLD_SILVER',						'REQUIRES_RESOURCE_COPPER_IN_PLOT'),
	('HD_PLOT_HAS_COPPER_GOLD_SILVER',						'REQUIRES_RESOURCE_GOLD_IN_PLOT'),
	('HD_PLOT_HAS_COPPER_GOLD_SILVER',						'REQUIRES_RESOURCE_SILVER_IN_PLOT'),
	-- 货栈
	-- 会馆
	('CITY_HAS_BUILDING_WORKSHOP',							'REQUIRES_CITY_HAS_BUILDING_WORKSHOP'),
	-- 贸易码头
	('HD_PLOT_HAS_SEA_LUXURY_RESOURCE_REQUIREMENTS',		'REQUIRES_PLOT_HAS_IMPROVED_LUXURY'),
	('HD_PLOT_HAS_SEA_LUXURY_RESOURCE_REQUIREMENTS',		'REQUIRES_PLOT_HAS_COAST'),
	('HD_PLOT_HAS_COAST_LUXURY_RESOURCE_REQUIREMENTS',		'REQUIRES_PLOT_HAS_IMPROVED_LUXURY'),
	('HD_PLOT_HAS_COAST_LUXURY_RESOURCE_REQUIREMENTS',		'HD_REQUIRES_PLOT_ADJACENT_TO_COAST'),
	('HD_PLOT_HAS_COAST_LUXURY_RESOURCE_REQUIREMENTS',		'REQUIRES_PLOT_HAS_NOT_COAST'),
	('HD_PLOT_HAS_SEA_BONUS_RESOURCE_REQUIREMENTS',			'REQUIRES_PLOT_HAS_IMPROVED_BONUS'),
	('HD_PLOT_HAS_SEA_BONUS_RESOURCE_REQUIREMENTS',			'REQUIRES_PLOT_HAS_COAST'),
	('HD_PLOT_HAS_COAST_BONUS_RESOURCE_REQUIREMENTS',		'REQUIRES_PLOT_HAS_IMPROVED_BONUS'),
	('HD_PLOT_HAS_COAST_BONUS_RESOURCE_REQUIREMENTS',		'HD_REQUIRES_PLOT_ADJACENT_TO_COAST'),
	('HD_PLOT_HAS_COAST_BONUS_RESOURCE_REQUIREMENTS',		'REQUIRES_PLOT_HAS_NOT_COAST'),
	-- 海港
	('HD_PLOT_HAS_FISHERY_OILWELL_WINDPOWER_SEASTEAD',		'REQUIRES_PLOT_HAS_IMPROVEMENT_FISHERY'),
	('HD_PLOT_HAS_FISHERY_OILWELL_WINDPOWER_SEASTEAD',		'HD_REQUIRES_PLOT_HAS_OFFSHORE_OIL_RIG'),
	('HD_PLOT_HAS_FISHERY_OILWELL_WINDPOWER_SEASTEAD',		'HD_REQUIRES_PLOT_HAS_OFFSHORE_WIND_FARM'),
	('HD_PLOT_HAS_FISHERY_OILWELL_WINDPOWER_SEASTEAD',		'HD_REQUIRES_PLOT_HAS_SEASTEAD'),
	-- 游轮码头
	('HD_ADJACENT_TO_ANY_ENTERTAINMENT_COMPLEX',			'REQUIRES_PLOT_ADJACENT_TO_DISTRICT_WATER_ENTERTAINMENT_COMPLEX'),
	('HD_ADJACENT_TO_ANY_ENTERTAINMENT_COMPLEX',			'REQUIRES_PLOT_ADJACENT_TO_DISTRICT_ENTERTAINMENT_COMPLEX');

-- insert or ignore into RequirementSetRequirements
-- 	(RequirementSetId,										RequirementId)
-- select
-- 	'HD_ADJACENT_TO_ANY_ENTERTAINMENT_COMPLEX',				'REQUIRES_PLOT_ADJACENT_TO_DISTRICT_HIPPODROME'
-- where exists ( select DistrictType from Districts where DistrictType = 'DISTRICT_HIPPODROME');

insert or ignore into Requirements
    (RequirementId,                        			RequirementType)
values
	('REQUIRES_PLOT_HAS_IMPROVED_LUXURY',			'REQUIREMENT_PLOT_IMPROVED_RESOURCE_CLASS_TYPE_MATCHES'),
	('REQUIRES_PLOT_HAS_IMPROVED_BONUS',			'REQUIREMENT_PLOT_IMPROVED_RESOURCE_CLASS_TYPE_MATCHES'),
    ('HD_REQUIRES_PLOT_HAS_OFFSHORE_OIL_RIG',       'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
    ('HD_REQUIRES_PLOT_HAS_OFFSHORE_WIND_FARM',     'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES'),
    ('HD_REQUIRES_PLOT_HAS_SEASTEAD',       		'REQUIREMENT_PLOT_IMPROVEMENT_TYPE_MATCHES');

insert or ignore into RequirementArguments
    (RequirementId,                        					Name,                Value)
values
	('REQUIRES_PLOT_HAS_IMPROVED_LUXURY',					'ResourceClassType', 'RESOURCECLASS_LUXURY'),
	('REQUIRES_PLOT_HAS_IMPROVED_BONUS',					'ResourceClassType', 'RESOURCECLASS_BONUS'),
    ('HD_REQUIRES_PLOT_HAS_OFFSHORE_OIL_RIG',       		'ImprovementType',   'IMPROVEMENT_OFFSHORE_OIL_RIG'),
    ('HD_REQUIRES_PLOT_HAS_OFFSHORE_WIND_FARM',     		'ImprovementType',   'IMPROVEMENT_OFFSHORE_WIND_FARM'),
    ('HD_REQUIRES_PLOT_HAS_SEASTEAD',       				'ImprovementType',   'IMPROVEMENT_SEASTEAD');

    -- 铸币厂
insert or replace into RequirementSetRequirements
	(RequirementSetId,					RequirementId)
select
	'HD_PLOT_HAS_COPPER_GOLD_SILVER',   'REQUIRES_RESOURCE_SEASHELLS_IN_PLOT'
where exists (select ResourceType from Resources where ResourceType = 'RESOURCE_SEASHELLS');

	-- 交易中心
insert or replace into Building_YieldDistrictCopies
	(BuildingType,							OldYieldType,			NewYieldType)
values
	('BUILDING_JNR_COMMODITY_EXCHANGE',		'YIELD_GOLD',			'YIELD_GOLD'),
	('BUILDING_JNR_FISH_MARKET',   			'YIELD_GOLD',   		'YIELD_GOLD');

	-- 商港
-- insert or replace into BuildingModifiers
-- 	(BuildingType,						ModifierId)
-- select
-- 	'BUILDING_JNR_FISH_MARKET',			'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_PRODUCTION'
-- from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

-- insert or replace into BuildingModifiers
-- 	(BuildingType,						ModifierId)
-- select
-- 	'BUILDING_JNR_FISH_MARKET',			'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_PRODUCTION2'
-- from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

-- insert or replace into BuildingModifiers
-- 	(BuildingType,						ModifierId)
-- select
-- 	'BUILDING_JNR_FISH_MARKET',			'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_GOLD'
-- from Resources where ResourceClassType in ('RESOURCECLASS_LUXURY','RESOURCECLASS_BONUS');

-- insert or replace into BuildingModifiers
-- 	(BuildingType,						ModifierId)
-- select
-- 	'BUILDING_JNR_FISH_MARKET',			'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_GOLD2'
-- from Resources where ResourceClassType in ('RESOURCECLASS_LUXURY','RESOURCECLASS_BONUS');

-- insert or replace into Modifiers
-- 	(ModifierId,													ModifierType,															SubjectRequirementSetId)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_PRODUCTION',	'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		'HD_CITY_HAS_IMPROVED_' || ResourceType || '_REQUIRMENTS'
-- from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

-- insert or replace into Modifiers
-- 	(ModifierId,													ModifierType,															SubjectRequirementSetId)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_PRODUCTION2',	'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',			'HD_CITY_HAS_IMPROVED_' || ResourceType || '_REQUIRMENTS'
-- from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

-- insert or replace into Modifiers
-- 	(ModifierId,													ModifierType,															SubjectRequirementSetId)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_GOLD',		'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',		'HD_CITY_HAS_IMPROVED_' || ResourceType || '_REQUIRMENTS'
-- from Resources where ResourceClassType in ('RESOURCECLASS_LUXURY','RESOURCECLASS_BONUS');

-- insert or replace into Modifiers
-- 	(ModifierId,													ModifierType,															SubjectRequirementSetId)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_GOLD2',		'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC',			'HD_CITY_HAS_IMPROVED_' || ResourceType || '_REQUIRMENTS'
-- from Resources where ResourceClassType in ('RESOURCECLASS_LUXURY','RESOURCECLASS_BONUS');

-- insert or replace into ModifierArguments
-- 	(ModifierId,													Name,			Value)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_PRODUCTION',	'YieldType',	'YIELD_PRODUCTION'
-- from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

-- insert or replace into ModifierArguments
-- 	(ModifierId,													Name,			Value)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_PRODUCTION',	'Amount',		1
-- from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

-- insert or replace into ModifierArguments
-- 	(ModifierId,													Name,			Value)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_PRODUCTION2',	'YieldType',	'YIELD_PRODUCTION'
-- from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

-- insert or replace into ModifierArguments
-- 	(ModifierId,													Name,			Value)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_PRODUCTION2',	'Amount',		1
-- from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

-- insert or replace into ModifierArguments
-- 	(ModifierId,													Name,			Value)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_GOLD',		'YieldType',	'YIELD_GOLD'
-- from Resources where ResourceClassType in ('RESOURCECLASS_LUXURY','RESOURCECLASS_BONUS');

-- insert or replace into ModifierArguments
-- 	(ModifierId,													Name,			Value)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_GOLD',		'Amount',		1
-- from Resources where ResourceClassType in ('RESOURCECLASS_LUXURY','RESOURCECLASS_BONUS');

-- insert or replace into ModifierArguments
-- 	(ModifierId,													Name,			Value)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_GOLD2',		'YieldType',	'YIELD_GOLD'
-- from Resources where ResourceClassType in ('RESOURCECLASS_LUXURY','RESOURCECLASS_BONUS');

-- insert or replace into ModifierArguments
-- 	(ModifierId,													Name,			Value)
-- select
-- 	'BUILDING_JNR_FISH_MARKET_'|| ResourceType ||'_TRADE_GOLD2',		'Amount',		1
-- from Resources where ResourceClassType in ('RESOURCECLASS_LUXURY','RESOURCECLASS_BONUS');


	-- 市场部：公司模式
delete from BuildingModifiers where (ModifierId = 'MARKETING_TOURISM_BONUS_TRADE' or ModifierId = 'MARKETING_TOURISM_BONUS_TRADE_POWERED')
	and exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

update Buildings set Description = 'LOC_BUILDING_JNR_MARKETING_AGENCY_MONOPOLY_DESCRIPTION' where BuildingType = 'BUILDING_JNR_MARKETING_AGENCY'
	and exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into BuildingModifiers
	(BuildingType,						ModifierId)
select
	'BUILDING_JNR_MARKETING_AGENCY',	'MARKETING_PRODUCT_TOURISM'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into Modifiers
	(ModifierId,									ModifierType)
select
	'MARKETING_PRODUCT_TOURISM',					'MODIFIER_SINGLE_CITY_ADJUST_TOURISM'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into ModifierArguments
	(ModifierId,									Name,						Value)
select
	'MARKETING_PRODUCT_TOURISM',					'GreatWorkObjectType',		'GREATWORKOBJECT_PRODUCT'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into ModifierArguments
	(ModifierId,									Name,						Value)
select
	'MARKETING_PRODUCT_TOURISM',					'ScalingFactor',			150
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');
	
insert or replace into BuildingModifiers
	(BuildingType,						ModifierId)
select
	'BUILDING_JNR_MARKETING_AGENCY',	'MARKETING_PRODUCT_TOURISM_POWERED'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into Modifiers
	(ModifierId,									ModifierType,										SubjectRequirementSetId)
select
	'MARKETING_PRODUCT_TOURISM_POWERED',			'MODIFIER_SINGLE_CITY_ADJUST_TOURISM',				'CITY_IS_POWERED'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into ModifierArguments
	(ModifierId,									Name,						Value)
select
	'MARKETING_PRODUCT_TOURISM_POWERED',			'GreatWorkObjectType',		'GREATWORKOBJECT_PRODUCT'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into ModifierArguments
	(ModifierId,									Name,						Value)
select
	'MARKETING_PRODUCT_TOURISM_POWERED',			'ScalingFactor',			150
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

	-- 游轮码头：公司模式
delete from BuildingModifiers where ModifierId = 'CRUISE_WATERPARK_DOUBLE_TOURISM'
	and exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

update Buildings set Description = 'LOC_BUILDING_JNR_OFFSHORE_TERMINAL_MONOPOLY_DESCRIPTION' where BuildingType = 'BUILDING_JNR_OFFSHORE_TERMINAL'
	and exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into BuildingModifiers
	(BuildingType,						ModifierId)
select
	'BUILDING_JNR_OFFSHORE_TERMINAL',		'CRUISE_TERMINAL_PRODUCT_TOURISM'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into Modifiers
	(ModifierId,									ModifierType)
select
	'CRUISE_TERMINAL_PRODUCT_TOURISM',				'MODIFIER_SINGLE_CITY_ADJUST_TOURISM'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into ModifierArguments
	(ModifierId,									Name,						Value)
select
	'CRUISE_TERMINAL_PRODUCT_TOURISM',				'GreatWorkObjectType',		'GREATWORKOBJECT_PRODUCT'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into ModifierArguments
	(ModifierId,									Name,						Value)
select
	'CRUISE_TERMINAL_PRODUCT_TOURISM',				'ScalingFactor',			150
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');
	
insert or replace into BuildingModifiers
	(BuildingType,						ModifierId)
select
	'BUILDING_JNR_OFFSHORE_TERMINAL',		'CRUISE_TERMINAL_PRODUCT_TOURISM_2'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into Modifiers
	(ModifierId,									ModifierType,										OwnerRequirementSetId)
select
	'CRUISE_TERMINAL_PRODUCT_TOURISM_2',			'MODIFIER_SINGLE_CITY_ADJUST_TOURISM',				'HD_ADJACENT_TO_ANY_ENTERTAINMENT_COMPLEX'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into ModifierArguments
	(ModifierId,									Name,						Value)
select
	'CRUISE_TERMINAL_PRODUCT_TOURISM_2',			'GreatWorkObjectType',		'GREATWORKOBJECT_PRODUCT'
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

insert or replace into ModifierArguments
	(ModifierId,									Name,						Value)
select
	'CRUISE_TERMINAL_PRODUCT_TOURISM_2',			'ScalingFactor',			150
where exists (select GreatWorkSlotType from GreatWorkSlotTypes where GreatWorkSlotType = 'GREATWORKSLOT_PRODUCT');

	-- 商港
--insert or replace into Modifiers
--	(ModifierId,									ModifierType,															SubjectRequirementSetId)
--values
--	('FREEPORT_TRADER_ATTACH',						'MODIFIER_PLAYER_UNITS_ATTACH_MODIFIER',								'UNIT_IS_TRADER'),
--	('FREEPORT_HARBOR_ATTACH',						'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',							'HARBOR_TRADER_WITHIN_FIVE_PLOTS'),
--	('FREEPORT_TRADER_WITHIN_FIVE_PLOTS_ADD_GOLD',	'MODIFIER_BUILDING_YIELD_CHANGE',										NULL);

--insert or replace into ModifierArguments
--	(ModifierId,									Name,						Value)
--values
--	('FREEPORT_TRADER_ATTACH',						'ModifierId',				'FREEPORT_HARBOR_ATTACH'),
--	('FREEPORT_HARBOR_ATTACH',						'ModifierId',				'FREEPORT_TRADER_WITHIN_FIVE_PLOTS_ADD_GOLD'),
--	('FREEPORT_TRADER_WITHIN_FIVE_PLOTS_ADD_GOLD',	'BuildingType',				'BUILDING_JNR_FISH_MARKET'),
--	('FREEPORT_TRADER_WITHIN_FIVE_PLOTS_ADD_GOLD',	'YieldType',				'YIELD_GOLD'),
--	('FREEPORT_TRADER_WITHIN_FIVE_PLOTS_ADD_GOLD',	'Amount',					3);

--insert or ignore into Requirements
--	(RequirementId,									RequirementType)
--values
--	('TRADER_WITHIN_FIVE_PLOTS',					'REQUIREMENT_PLOT_ADJACENT_TO_OWNER');

--insert or ignore into RequirementArguments
--	(RequirementId,									Name,						Value)
--values
--	('TRADER_WITHIN_FIVE_PLOTS',					'MinDistance',				0),
--	('TRADER_WITHIN_FIVE_PLOTS',					'MaxDistance',				5);

--insert or ignore into RequirementSets
--	(RequirementSetId,								RequirementSetType)
--values
--	('HARBOR_TRADER_WITHIN_FIVE_PLOTS',				'REQUIREMENTSET_TEST_ALL');

--insert or ignore into RequirementSetRequirements
--	(RequirementSetId,								RequirementId)
--values
--	('HARBOR_TRADER_WITHIN_FIVE_PLOTS',				'REQUIRES_DISTRICT_IS_DISTRICT_HARBOR'),
--	('HARBOR_TRADER_WITHIN_FIVE_PLOTS',				'TRADER_WITHIN_FIVE_PLOTS');

--insert or replace into TraitModifiers
--	(TraitType,										ModifierId)
--values
--	('TRAIT_LEADER_MAJOR_CIV',						'FREEPORT_TRADER_ATTACH');

	-- 海港
-- insert or replace into BuildingModifiers
-- 	(BuildingType,										ModifierId)
-- select
-- 	'BUILDING_SEAPORT',									'SEAPORT_PURCHASE_' || UnitType || '_DISCOUNT'
-- from Units where Domain = 'DOMAIN_SEA';

-- insert or replace into Modifiers
-- 	(ModifierId,										ModifierType)
-- select
-- 	'SEAPORT_PURCHASE_' || UnitType || '_DISCOUNT',		'MODIFIER_SINGLE_CITY_ADJUST_UNIT_PURCHASE_COST'
-- from Units where Domain = 'DOMAIN_SEA';

-- insert or replace into ModifierArguments
-- 	(ModifierId,										Name,					Value)
-- select
-- 	'SEAPORT_PURCHASE_' || UnitType || '_DISCOUNT',		'UnitType',				UnitType
-- from Units where Domain = 'DOMAIN_SEA';

-- insert or replace into ModifierArguments
-- 	(ModifierId,										Name,					Value)
-- select
-- 	'SEAPORT_PURCHASE_' || UnitType || '_DISCOUNT',		'Amount',				25
-- from Units where Domain = 'DOMAIN_SEA';
--------------------------------------------------------------

-- 尤里卡/鼓舞改动
--------------------------------------------------------------
	-- 资本主义
update Boosts set NumItems = 1, TriggerDescription = 'LOC_BOOST_TRIGGER_CAPITALISM_HD' where CivicType = 'CIVIC_CAPITALISM';

	-- 公会
update Boosts set BuildingType = NULL, DistrictType = 'DISTRICT_COMMERCIAL_HUB', BoostClass = 'BOOST_TRIGGER_HAVE_X_DISTRICTS',
	TriggerDescription = 'LOC_BOOST_TRIGGER_GUILDS_HD' where CivicType = 'CIVIC_GUILDS';

	-- 经济
update Boosts set TriggerDescription = 'LOC_BOOST_TRIGGER_ECONOMICS_HD', TriggerLongDescription = 'LOC_BOOST_TRIGGER_LONGDESC_ECONOMICS_HD' where TechnologyType = 'TECH_ECONOMICS';

insert or ignore into Requirements
	(RequirementId,										RequirementType)
values
	('REQUIRES_PLAYER_HAS_2_GUILDHALL_JNR',				'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_BUILDINGS'),
	('REQUIRES_PLAYER_HAS_2_MERCHANT_JNR',				'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_BUILDINGS'),
	('REQUIRES_PLAYER_HAS_GUILDHALL_JNR',				'REQUIREMENT_PLAYER_HAS_BUILDING'),
	('REQUIRES_PLAYER_HAS_MERCHANT_JNR',				'REQUIREMENT_PLAYER_HAS_BUILDING'),
	('REQUIRES_PLAYER_HAS_BANK_JNR',					'REQUIREMENT_REQUIREMENTSET_IS_MET'),
	('REQUIRES_PLAYER_HAS_BANK',						'REQUIREMENT_PLAYER_HAS_BUILDING'),
	('REQUIRES_PLAYER_HAS_GRAND_BAZAAR',				'REQUIREMENT_PLAYER_HAS_BUILDING');

insert or ignore into RequirementArguments
	(RequirementId,										Name,				Value)
values
	('REQUIRES_PLAYER_HAS_2_GUILDHALL_JNR',				'BuildingType',		'BUILDING_JNR_GUILDHALL'),
	('REQUIRES_PLAYER_HAS_2_GUILDHALL_JNR',				'Amount',			2),
	('REQUIRES_PLAYER_HAS_2_MERCHANT_JNR',				'BuildingType',		'BUILDING_JNR_MERCHANT_QUARTER'),
	('REQUIRES_PLAYER_HAS_2_MERCHANT_JNR',				'Amount',			2),
	('REQUIRES_PLAYER_HAS_GUILDHALL_JNR',				'BuildingType',		'BUILDING_JNR_GUILDHALL'),
	('REQUIRES_PLAYER_HAS_MERCHANT_JNR',				'BuildingType',		'BUILDING_JNR_MERCHANT_QUARTER'),
	('REQUIRES_PLAYER_HAS_BANK',						'BuildingType',		'BUILDING_BANK'),
	('REQUIRES_PLAYER_HAS_GRAND_BAZAAR',				'BuildingType',		'BUILDING_GRAND_BAZAAR'),
	('REQUIRES_PLAYER_HAS_BANK_JNR',					'RequirementSetId',	'REQUIRES_PLAYER_HAS_BANK_UBMET');

insert or ignore into RequirementSets
	(RequirementSetId,											RequirementSetType)
values
	('PLAYER_HAS_2_GUILDHALL_REQUIREMENT_JNR',					'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_HAS_2_MERCHANT_REQUIREMENT_JNR',					'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_HAS_GUILDHALL_AND_BANK_REQUIREMENT_JNR',			'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_HAS_GUILDHALL_AND_MERCHANT_REQUIREMENT_JNR',		'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_HAS_BANK_AND_MERCHANT_REQUIREMENT_JNR',			'REQUIREMENTSET_TEST_ALL'),
	('REQUIRES_PLAYER_HAS_BANK_UBMET',							'REQUIREMENTSET_TEST_ANY');

insert or ignore into RequirementSetRequirements
	(RequirementSetId,											RequirementId)
values
	('PLAYER_HAS_2_GUILDHALL_REQUIREMENT_JNR',					'REQUIRES_PLAYER_HAS_2_GUILDHALL_JNR'),
	('PLAYER_HAS_2_MERCHANT_REQUIREMENT_JNR',					'REQUIRES_PLAYER_HAS_2_MERCHANT_JNR'),
	('PLAYER_HAS_GUILDHALL_AND_BANK_REQUIREMENT_JNR',			'REQUIRES_PLAYER_HAS_GUILDHALL_JNR'),
	('PLAYER_HAS_GUILDHALL_AND_BANK_REQUIREMENT_JNR',			'REQUIRES_PLAYER_HAS_BANK_JNR'),
	('PLAYER_HAS_GUILDHALL_AND_MERCHANT_REQUIREMENT_JNR',		'REQUIRES_PLAYER_HAS_GUILDHALL_JNR'),
	('PLAYER_HAS_GUILDHALL_AND_MERCHANT_REQUIREMENT_JNR',		'REQUIRES_PLAYER_HAS_MERCHANT_JNR'),
	('PLAYER_HAS_BANK_AND_MERCHANT_REQUIREMENT_JNR',			'REQUIRES_PLAYER_HAS_MERCHANT_JNR'),
	('PLAYER_HAS_BANK_AND_MERCHANT_REQUIREMENT_JNR',			'REQUIRES_PLAYER_HAS_BANK_JNR'),
	('REQUIRES_PLAYER_HAS_BANK_UBMET',							'REQUIRES_PLAYER_HAS_BANK'),
	('REQUIRES_PLAYER_HAS_BANK_UBMET',							'REQUIRES_PLAYER_HAS_GRAND_BAZAAR');

insert or replace into Modifiers
	(ModifierId,                                    ModifierType,                                           SubjectRequirementSetId,                            Permanent,  RunOnce)
values
	('ECONOMICS_TECHBOOST_2_GUILDHALL_JNR',			'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_2_GUILDHALL_REQUIREMENT_JNR',			1,			1),
	('ECONOMICS_TECHBOOST_2_MERCHANT_JNR',			'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_2_MERCHANT_REQUIREMENT_JNR',			1,			1),
	('ECONOMICS_TECHBOOST_BANK_GUILDHALL_JNR',		'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_GUILDHALL_AND_BANK_REQUIREMENT_JNR',	1,			1),
	('ECONOMICS_TECHBOOST_MERCHANT_GUILDHALL_JNR',	'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_GUILDHALL_AND_MERCHANT_REQUIREMENT_JNR',1,			1),
	('ECONOMICS_TECHBOOST_BANK_MERCHANT_JNR',		'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_BANK_AND_MERCHANT_REQUIREMENT_JNR',		1,			1);

insert or replace into ModifierArguments
	(ModifierId,									Name,				Value)
values
	('ECONOMICS_TECHBOOST_2_GUILDHALL_JNR',			'TechType',			'TECH_ECONOMICS'),
	('ECONOMICS_TECHBOOST_2_MERCHANT_JNR',			'TechType',			'TECH_ECONOMICS'),
	('ECONOMICS_TECHBOOST_BANK_GUILDHALL_JNR',		'TechType',			'TECH_ECONOMICS'),
	('ECONOMICS_TECHBOOST_MERCHANT_GUILDHALL_JNR',	'TechType',			'TECH_ECONOMICS'),
	('ECONOMICS_TECHBOOST_BANK_MERCHANT_JNR',		'TechType',			'TECH_ECONOMICS');

insert or replace into TraitModifiers
	(TraitType,                 ModifierId)
values
	('TRAIT_LEADER_MAJOR_CIV',	'ECONOMICS_TECHBOOST_2_GUILDHALL_JNR'),
	('TRAIT_LEADER_MAJOR_CIV',	'ECONOMICS_TECHBOOST_2_MERCHANT_JNR'),
	('TRAIT_LEADER_MAJOR_CIV',	'ECONOMICS_TECHBOOST_BANK_GUILDHALL_JNR'),
	('TRAIT_LEADER_MAJOR_CIV',	'ECONOMICS_TECHBOOST_MERCHANT_GUILDHALL_JNR'),
	('TRAIT_LEADER_MAJOR_CIV',	'ECONOMICS_TECHBOOST_BANK_MERCHANT_JNR');

	-- 蒸汽动力
update Boosts set TriggerDescription = 'LOC_BOOST_TRIGGER_STEAM_POWER_HD', TriggerLongDescription = 'LOC_BOOST_TRIGGER_LONGDESC_STEAM_POWER_HD' where TechnologyType = 'TECH_STEAM_POWER';

insert or ignore into Requirements
	(RequirementId,										RequirementType)
values
	('REQUIRES_PLAYER_HAS_2_JNR_HAVEN_JNR',				'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_BUILDINGS'),
	('REQUIRES_PLAYER_HAS_2_JNR_FREEPORT_JNR',			'REQUIREMENT_PLAYER_HAS_AT_LEAST_NUM_BUILDINGS'),
	('REQUIRES_PLAYER_HAS_JNR_HAVEN_JNR',				'REQUIREMENT_PLAYER_HAS_BUILDING'),
	('REQUIRES_PLAYER_HAS_JNR_FREEPORT_JNR',			'REQUIREMENT_PLAYER_HAS_BUILDING'),
	('REQUIRES_PLAYER_HAS_SHIPYARD_JNR',				'REQUIREMENT_PLAYER_HAS_BUILDING');

insert or ignore into RequirementArguments
	(RequirementId,										Name,				Value)
values
	('REQUIRES_PLAYER_HAS_2_JNR_HAVEN_JNR',				'BuildingType',		'BUILDING_JNR_ENTREPOT'),
	('REQUIRES_PLAYER_HAS_2_JNR_HAVEN_JNR',				'Amount',			2),
	('REQUIRES_PLAYER_HAS_2_JNR_FREEPORT_JNR',			'BuildingType',		'BUILDING_JNR_FISH_MARKET'),
	('REQUIRES_PLAYER_HAS_2_JNR_FREEPORT_JNR',			'Amount',			2),
	('REQUIRES_PLAYER_HAS_JNR_HAVEN_JNR',				'BuildingType',		'BUILDING_JNR_ENTREPOT'),
	('REQUIRES_PLAYER_HAS_JNR_FREEPORT_JNR',			'BuildingType',		'BUILDING_JNR_FISH_MARKET'),
	('REQUIRES_PLAYER_HAS_SHIPYARD_JNR',				'BuildingType',		'BUILDING_SHIPYARD');

insert or ignore into RequirementSets
	(RequirementSetId,											RequirementSetType)
values
	('PLAYER_HAS_2_JNR_HAVEN_REQUIREMENT_JNR',					'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_HAS_2_JNR_FREEPORT_REQUIREMENT_JNR',				'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_HAS_JNR_HAVEN_AND_SHIPYARD_REQUIREMENT_JNR',		'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_HAS_JNR_HAVEN_AND_JNR_FREEPORT_REQUIREMENT_JNR',	'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_HAS_SHIPYARD_AND_JNR_FREEPORT_REQUIREMENT_JNR',	'REQUIREMENTSET_TEST_ALL');

insert or ignore into RequirementSetRequirements
	(RequirementSetId,											RequirementId)
values
	('PLAYER_HAS_2_JNR_HAVEN_REQUIREMENT_JNR',					'REQUIRES_PLAYER_HAS_2_JNR_HAVEN_JNR'),
	('PLAYER_HAS_2_JNR_FREEPORT_REQUIREMENT_JNR',				'REQUIRES_PLAYER_HAS_2_JNR_FREEPORT_JNR'),
	('PLAYER_HAS_JNR_HAVEN_AND_SHIPYARD_REQUIREMENT_JNR',		'REQUIRES_PLAYER_HAS_JNR_HAVEN_JNR'),
	('PLAYER_HAS_JNR_HAVEN_AND_SHIPYARD_REQUIREMENT_JNR',		'REQUIRES_PLAYER_HAS_SHIPYARD_JNR'),
	('PLAYER_HAS_JNR_HAVEN_AND_JNR_FREEPORT_REQUIREMENT_JNR',	'REQUIRES_PLAYER_HAS_JNR_HAVEN_JNR'),
	('PLAYER_HAS_JNR_HAVEN_AND_JNR_FREEPORT_REQUIREMENT_JNR',	'REQUIRES_PLAYER_HAS_JNR_FREEPORT_JNR'),
	('PLAYER_HAS_SHIPYARD_AND_JNR_FREEPORT_REQUIREMENT_JNR',	'REQUIRES_PLAYER_HAS_JNR_FREEPORT_JNR'),
	('PLAYER_HAS_SHIPYARD_AND_JNR_FREEPORT_REQUIREMENT_JNR',	'REQUIRES_PLAYER_HAS_SHIPYARD_JNR');

insert or replace into Modifiers
	(ModifierId,                                    		ModifierType,                                           SubjectRequirementSetId,                           		Permanent,  RunOnce)
values
	('STEAM_POWER_TECHBOOST_2_JNR_HAVEN_JNR',				'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_2_JNR_HAVEN_REQUIREMENT_JNR',				1,			1),
	('STEAM_POWER_TECHBOOST_2_JNR_FREEPORT_JNR',			'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_2_JNR_FREEPORT_REQUIREMENT_JNR',			1,			1),
	('STEAM_POWER_TECHBOOST_SHIPYARD_JNR_HAVEN_JNR',		'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_JNR_HAVEN_AND_SHIPYARD_REQUIREMENT_JNR',	1,			1),
	('STEAM_POWER_TECHBOOST_JNR_FREEPORT_JNR_HAVEN_JNR',	'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_JNR_HAVEN_AND_JNR_FREEPORT_REQUIREMENT_JNR',1,			1),
	('STEAM_POWER_TECHBOOST_SHIPYARD_JNR_FREEPORT_JNR',		'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_SHIPYARD_AND_JNR_FREEPORT_REQUIREMENT_JNR',	1,			1);

insert or replace into ModifierArguments
	(ModifierId,											Name,				Value)
values
	('STEAM_POWER_TECHBOOST_2_JNR_HAVEN_JNR',				'TechType',			'TECH_STEAM_POWER'),
	('STEAM_POWER_TECHBOOST_2_JNR_FREEPORT_JNR',			'TechType',			'TECH_STEAM_POWER'),
	('STEAM_POWER_TECHBOOST_SHIPYARD_JNR_HAVEN_JNR',		'TechType',			'TECH_STEAM_POWER'),
	('STEAM_POWER_TECHBOOST_JNR_FREEPORT_JNR_HAVEN_JNR',	'TechType',			'TECH_STEAM_POWER'),
	('STEAM_POWER_TECHBOOST_SHIPYARD_JNR_FREEPORT_JNR',		'TechType',			'TECH_STEAM_POWER');

insert or replace into TraitModifiers
	(TraitType,                 ModifierId)
values
	('TRAIT_LEADER_MAJOR_CIV',	'STEAM_POWER_TECHBOOST_2_JNR_HAVEN_JNR'),
	('TRAIT_LEADER_MAJOR_CIV',	'STEAM_POWER_TECHBOOST_2_JNR_FREEPORT_JNR'),
	('TRAIT_LEADER_MAJOR_CIV',	'STEAM_POWER_TECHBOOST_SHIPYARD_JNR_HAVEN_JNR'),
	('TRAIT_LEADER_MAJOR_CIV',	'STEAM_POWER_TECHBOOST_JNR_FREEPORT_JNR_HAVEN_JNR'),
	('TRAIT_LEADER_MAJOR_CIV',	'STEAM_POWER_TECHBOOST_SHIPYARD_JNR_FREEPORT_JNR');
--------------------------------------------------------------

-- 城邦使者加成改动
--------------------------------------------------------------
insert or ignore into RequirementSetRequirements
	(RequirementSetId,												RequirementId)
values
	-- City State
	('HD_CITY_HAS_TRADE_TIER_1_BUILDING_REQUIREMENTS',		       	'REQUIRES_CITY_HAS_BUILDING_JNR_MINT'),
	('HD_CITY_HAS_TRADE_TIER_1_BUILDING_REQUIREMENTS',		       	'REQUIRES_CITY_HAS_BUILDING_JNR_WAYSTATION'),
    ('HD_CITY_HAS_TRADE_TIER_2_BUILDING_REQUIREMENTS',		       	'REQUIRES_CITY_HAS_BUILDING_JNR_GUILDHALL'),
    ('HD_CITY_HAS_TRADE_TIER_2_BUILDING_REQUIREMENTS',		       	'REQUIRES_CITY_HAS_BUILDING_JNR_MERCHANT_QUARTER'),
    ('HD_CITY_HAS_TRADE_TIER_3_BUILDING_REQUIREMENTS',		       	'REQUIRES_CITY_HAS_BUILDING_JNR_COMMODITY_EXCHANGE'),
    ('HD_CITY_HAS_TRADE_TIER_3_BUILDING_REQUIREMENTS',		       	'REQUIRES_CITY_HAS_BUILDING_JNR_MARKETING_AGENCY'),

    ('HD_CITY_HAS_TRADE_TIER_1_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_LIGHTHOUSE_FISHING'),
    ('HD_CITY_HAS_TRADE_TIER_2_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_ENTREPOT'),
    ('HD_CITY_HAS_TRADE_TIER_2_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_FISH_MARKET'),
    ('HD_CITY_HAS_TRADE_TIER_3_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_OFFSHORE_TERMINAL'),
    ('HD_CITY_HAS_TRADE_TIER_3_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_NAVAL_BASE'),
    -- Policy
    ('HD_CITY_HAS_COMMERCIAL_TIER_1_BUILDING_REQUIREMENTS',		    'REQUIRES_CITY_HAS_BUILDING_MARKET'),
    ('HD_CITY_HAS_COMMERCIAL_TIER_1_BUILDING_REQUIREMENTS',		    'REQUIRES_CITY_HAS_BUILDING_JNR_MINT'),
	('HD_CITY_HAS_COMMERCIAL_TIER_1_BUILDING_REQUIREMENTS',		    'REQUIRES_CITY_HAS_BUILDING_JNR_WAYSTATION'),
	('HD_CITY_HAS_COMMERCIAL_TIER_2_BUILDING_REQUIREMENTS',		    'REQUIRES_CITY_HAS_BUILDING_BANK'),
    ('HD_CITY_HAS_COMMERCIAL_TIER_2_BUILDING_REQUIREMENTS',		    'REQUIRES_CITY_HAS_BUILDING_JNR_GUILDHALL'),
    ('HD_CITY_HAS_COMMERCIAL_TIER_2_BUILDING_REQUIREMENTS',		    'REQUIRES_CITY_HAS_BUILDING_JNR_MERCHANT_QUARTER'),
    ('HD_CITY_HAS_COMMERCIAL_TIER_3_BUILDING_REQUIREMENTS',		    'REQUIRES_CITY_HAS_BUILDING_STOCK_EXCHANGE'),
    ('HD_CITY_HAS_COMMERCIAL_TIER_3_BUILDING_REQUIREMENTS',		    'REQUIRES_CITY_HAS_BUILDING_JNR_COMMODITY_EXCHANGE'),
    ('HD_CITY_HAS_COMMERCIAL_TIER_3_BUILDING_REQUIREMENTS',		    'REQUIRES_CITY_HAS_BUILDING_JNR_MARKETING_AGENCY'),

    ('HD_CITY_HAS_HARBOR_TIER_1_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_LIGHTHOUSE'),
    ('HD_CITY_HAS_HARBOR_TIER_1_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_LIGHTHOUSE_FISHING'),
    ('HD_CITY_HAS_HARBOR_TIER_2_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_SHIPYARD'),
    ('HD_CITY_HAS_HARBOR_TIER_2_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_ENTREPOT'),
    ('HD_CITY_HAS_HARBOR_TIER_2_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_FISH_MARKET'),
    ('HD_CITY_HAS_HARBOR_TIER_3_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_SEAPORT'),
    ('HD_CITY_HAS_HARBOR_TIER_3_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_OFFSHORE_TERMINAL'),
    ('HD_CITY_HAS_HARBOR_TIER_3_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_NAVAL_BASE');

    -- CSE 海洋城邦适配
update RequirementSetRequirements set RequirementSetId = 'HD_CITY_HAS_CSE_MARITIME_TIER_1_BUILDING_REQUIREMENTS'
where exists (select Type from CSE_ClassTypes where Type = 'CSE_MARITIME') and 
    (RequirementSetId = 'HD_CITY_HAS_TRADE_TIER_1_BUILDING_REQUIREMENTS' and RequirementId = 'REQUIRES_CITY_HAS_BUILDING_JNR_LIGHTHOUSE_FISHING');

update RequirementSetRequirements set RequirementSetId = 'HD_CITY_HAS_CSE_MARITIME_TIER_2_BUILDING_REQUIREMENTS'
where exists (select Type from CSE_ClassTypes where Type = 'CSE_MARITIME') and 
    (RequirementSetId = 'HD_CITY_HAS_TRADE_TIER_2_BUILDING_REQUIREMENTS' and RequirementId = 'REQUIRES_CITY_HAS_BUILDING_JNR_ENTREPOT');

update RequirementSetRequirements set RequirementSetId = 'HD_CITY_HAS_CSE_MARITIME_TIER_2_BUILDING_REQUIREMENTS'
where exists (select Type from CSE_ClassTypes where Type = 'CSE_MARITIME') and 
    (RequirementSetId = 'HD_CITY_HAS_TRADE_TIER_2_BUILDING_REQUIREMENTS' and RequirementId = 'REQUIRES_CITY_HAS_BUILDING_JNR_FISH_MARKET');

update RequirementSetRequirements set RequirementSetId = 'HD_CITY_HAS_CSE_MARITIME_TIER_3_BUILDING_REQUIREMENTS'
where exists (select Type from CSE_ClassTypes where Type = 'CSE_MARITIME') and 
    (RequirementSetId = 'HD_CITY_HAS_TRADE_TIER_3_BUILDING_REQUIREMENTS' and RequirementId = 'REQUIRES_CITY_HAS_BUILDING_JNR_OFFSHORE_TERMINAL');

update RequirementSetRequirements set RequirementSetId = 'HD_CITY_HAS_CSE_MARITIME_TIER_3_BUILDING_REQUIREMENTS'
where exists (select Type from CSE_ClassTypes where Type = 'CSE_MARITIME') and 
    (RequirementSetId = 'HD_CITY_HAS_TRADE_TIER_3_BUILDING_REQUIREMENTS' and RequirementId = 'REQUIRES_CITY_HAS_BUILDING_JNR_NAVAL_BASE');
--------------------------------------------------------------

-- 政策卡改动
--------------------------------------------------------------
	-- 自由市场
-- update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_COMMERCIAL_TIER_2_BUILDING_REQUIREMENTS' where ModifierId = 'POLICY_FREE_MARKET_BANK_POPULATION_GOLD';
-- update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_COMMERCIAL_TIER_3_BUILDING_REQUIREMENTS' where ModifierId = 'POLICY_FREE_MARKET_STOCK_EXCHANGE_POPULATION_GOLD';

	-- 海军红卡
update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_HARBOR_TIER_1_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_LIGHTHOUSE' and ModifierType = 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION';
update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_HARBOR_TIER_2_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_SHIPYARD' and ModifierType = 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION';
update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_HARBOR_TIER_3_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_SEAPORT' and ModifierType = 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION';

-- 	-- 军事研究
-- insert or replace into PolicyModifiers
-- 	(PolicyType,					ModifierId)
-- values
-- 	('POLICY_MILITARY_RESEARCH',	'MILITARYRESEARCH_CRUISE_TERMINAL_SCIENCE_MODIFIER'),
-- 	('POLICY_MILITARY_RESEARCH',	'MILITARYRESEARCH_NAVAL_BASE_SCIENCE_MODIFIER');

-- insert or replace into Modifiers
-- 	(ModifierId,												ModifierType)
-- values
-- 	('MILITARYRESEARCH_CRUISE_TERMINAL_SCIENCE_MODIFIER',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
-- 	('MILITARYRESEARCH_NAVAL_BASE_SCIENCE_MODIFIER',			'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE');

-- insert or replace into ModifierArguments
-- 	(ModifierId,												Name,					Value)
-- values
-- 	('MILITARYRESEARCH_CRUISE_TERMINAL_SCIENCE_MODIFIER',		'BuildingType',			'BUILDING_JNR_OFFSHORE_TERMINAL'),
-- 	('MILITARYRESEARCH_CRUISE_TERMINAL_SCIENCE_MODIFIER',		'YieldType',			'YIELD_SCIENCE'),
-- 	('MILITARYRESEARCH_CRUISE_TERMINAL_SCIENCE_MODIFIER',		'Amount',				5),
-- 	('MILITARYRESEARCH_NAVAL_BASE_SCIENCE_MODIFIER',			'BuildingType',			'BUILDING_JNR_NAVAL_BASE'),
-- 	('MILITARYRESEARCH_NAVAL_BASE_SCIENCE_MODIFIER',			'YieldType',			'YIELD_SCIENCE'),
-- 	('MILITARYRESEARCH_NAVAL_BASE_SCIENCE_MODIFIER',			'Amount',				5);

	-- 一体化空间结构
insert or ignore into RequirementSetRequirements
	(RequirementSetId,											RequirementId)
values
	('CITY_HAS_MILITARY_ACADEMY_OR_SEAPORT',					'REQUIRES_CITY_HAS_BUILDING_JNR_OFFSHORE_TERMINAL'),
	('CITY_HAS_MILITARY_ACADEMY_OR_SEAPORT',					'REQUIRES_CITY_HAS_BUILDING_JNR_NAVAL_BASE');

	-- 伟人卡
-- update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_HARBOR_TIER_1_BUILDING_REQUIREMENTS' where ModifierId = 'NAVIGATION_ADMIRAL_LIGHTHOUSE';
-- update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_COMMERCIAL_TIER_1_BUILDING_REQUIREMENTS' where ModifierId = 'TRAVELING_MERCHANTS_MARKET';
-- update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_HARBOR_TIER_2_BUILDING_REQUIREMENTS' where ModifierId = 'LAISSEZFAIRE_ADMIRAL_SHIPYARD';
-- update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_COMMERCIAL_TIER_2_BUILDING_REQUIREMENTS' where ModifierId = 'LAISSEZFAIRE_MERCHANT_BANK';
-- update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_HARBOR_TIER_3_BUILDING_REQUIREMENTS' where ModifierId = 'LAISSEZFAIRE_ADMIRAL_SEAPORT';
-- update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_COMMERCIAL_TIER_3_BUILDING_REQUIREMENTS' where ModifierId = 'LAISSEZFAIRE_MERCHANT_STOCKEXCHANGE';
--------------------------------------------------------------

-- 伟人改动
--------------------------------------------------------------
	-- 阿特尔米希亚
insert or replace into GreatPersonIndividualActionModifiers
	(GreatPersonIndividualType,							ModifierId,												AttachmentTargetType)
values
    ('GREAT_PERSON_INDIVIDUAL_ARTEMISIA',               'ARTEMISIA_LIGHTHOUSE_TRADE_GOLD',          			'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE');

insert or replace into Modifiers
    (ModifierId,                                        ModifierType,                                           RunOnce,    Permanent)
values
    ('ARTEMISIA_LIGHTHOUSE_TRADE_GOLD',                 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',  0,          1);

update ModifierArguments set Value = 'BUILDING_JNR_LIGHTHOUSE_FISHING' where ModifierId in ('ARTEMISIA_LIGHTHOUSE', 'ARTEMISIA_LIGHTHOUSE_FOOD') and Name = 'BuildingType';
insert or replace into ModifierArguments
    (ModifierId,                                        Name,               Value)
values
    ('ARTEMISIA_LIGHTHOUSE_TRADE_GOLD',                 'BuildingType',     'BUILDING_LIGHTHOUSE'),
    ('ARTEMISIA_LIGHTHOUSE_TRADE_GOLD',                 'YieldType',        'YIELD_GOLD'),
    ('ARTEMISIA_LIGHTHOUSE_TRADE_GOLD',                 'Amount',           3);

insert or replace into ModifierStrings
    (ModifierId,                                        Context,    Text)
values
    ('ARTEMISIA_LIGHTHOUSE_TRADE_GOLD',                 'Summary',  'LOC_ARTEMISIA_TRADE_PORT_GOLD');

update ModifierStrings set Text = 'LOC_ARTEMISIA_FISHING_PORT_FOOD' where Text = 'LOC_ARTEMISIA_LIGHTHOUSE_FOOD' and ModifierId = 'ARTEMISIA_LIGHTHOUSE_FOOD';

	-- 霍雷肖·纳尔逊
insert or replace into GreatPersonIndividualActionModifiers
	(GreatPersonIndividualType,							ModifierId,												AttachmentTargetType)
values
    ('GREAT_PERSON_INDIVIDUAL_HORATIO_NELSON',		   'HORATIO_NELSON_HAVEN_PRODUCTION',         	 			'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
    ('GREAT_PERSON_INDIVIDUAL_HORATIO_NELSON',		   'HORATIO_NELSON_FREEPORT_PRODUCTION',  	        		'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER');

insert or replace into Modifiers
    (ModifierId,                                        ModifierType,                                           RunOnce,    Permanent)
values
    ('HORATIO_NELSON_HAVEN_PRODUCTION',                	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',  0,          1),
    ('HORATIO_NELSON_FREEPORT_PRODUCTION',              'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',  0,          1);

insert or replace into ModifierArguments
    (ModifierId,                                        Name,               Value)
values
    ('HORATIO_NELSON_HAVEN_PRODUCTION', 		        'BuildingType',     'BUILDING_JNR_ENTREPOT'),
    ('HORATIO_NELSON_HAVEN_PRODUCTION', 		        'YieldType',        'YIELD_PRODUCTION'),
    ('HORATIO_NELSON_HAVEN_PRODUCTION', 		        'Amount',           3),
    ('HORATIO_NELSON_FREEPORT_PRODUCTION', 		        'BuildingType',     'BUILDING_JNR_FISH_MARKET'),
    ('HORATIO_NELSON_FREEPORT_PRODUCTION', 		        'YieldType',        'YIELD_PRODUCTION'),
    ('HORATIO_NELSON_FREEPORT_PRODUCTION', 		        'Amount',           3);

update ModifierStrings set Text = 'LOC_GREATPERSON_HORATIO_NELSON_JNR_ACTIVE' where Text = 'LOC_GREATPERSON_HORATIO_NELSON_EXPANSION2_ACTIVE' and ModifierId = 'GREATPERSON_HORATIO_NELSON_ACTIVE';
update ModifierStrings set Text = 'LOC_HORATIO_NELSON_TIER2_PRODUCTION' where Text = 'LOC_HORATIO_NELSON_SHIPYARD_PRODUCTION' and ModifierId = 'HORATIO_NELSON_SHIPYARD_PRODUCTION';    

	-- 若阿金·马奎斯·葡京
update GreatPersonIndividualActionModifiers set ModifierId = 'LISBOA_GRANT_HAVEN' where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_JOAQUIM_MARQUES_LISBOA' and ModifierId = 'GREATPERSON_HORATIO_NELSON_SHIPYARD';
update ModifierArguments set Value = 'BUILDING_JNR_NAVAL_BASE' where Name = 'BuildingType' and ModifierId = 'GREATPERSON_JOAQUIM_MARQUES_LISBOA_SEAPORT';

insert or replace into GreatPersonIndividualActionModifiers
	(GreatPersonIndividualType,							ModifierId,												AttachmentTargetType)
values
    ('GREAT_PERSON_INDIVIDUAL_JOAQUIM_MARQUES_LISBOA',  'LISBOA_FREEPORT_PRODUCTION',         	 				'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
    ('GREAT_PERSON_INDIVIDUAL_JOAQUIM_MARQUES_LISBOA',  'LISBOA_CRUISE_TERMINAL_PRODUCTION',  	        		'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
    ('GREAT_PERSON_INDIVIDUAL_JOAQUIM_MARQUES_LISBOA',  'LISBOA_NAVAL_BASE_PRODUCTION',       	   				'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER');

insert or replace into Modifiers
    (ModifierId,                                        ModifierType,                                           RunOnce,    Permanent)
values
	('LISBOA_GRANT_HAVEN',		                		'MODIFIER_SINGLE_CITY_GRANT_BUILDING_IN_CITY_IGNORE',   1,          1),
    ('LISBOA_FREEPORT_PRODUCTION',                		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',  0,          1),
    ('LISBOA_CRUISE_TERMINAL_PRODUCTION',               'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',  0,          1),
    ('LISBOA_NAVAL_BASE_PRODUCTION',                 	'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE',  0,          1);

insert or replace into ModifierArguments
    (ModifierId,                                        Name,               Value)
values
	('LISBOA_GRANT_HAVEN', 		               		    'BuildingType',     'BUILDING_JNR_ENTREPOT'),
    ('LISBOA_FREEPORT_PRODUCTION', 		                'BuildingType',     'BUILDING_SEAPORT'),
    ('LISBOA_FREEPORT_PRODUCTION', 		                'YieldType',        'YIELD_PRODUCTION'),
    ('LISBOA_FREEPORT_PRODUCTION', 		                'Amount',           4),
    ('LISBOA_CRUISE_TERMINAL_PRODUCTION', 		        'BuildingType',     'BUILDING_JNR_OFFSHORE_TERMINAL'),
    ('LISBOA_CRUISE_TERMINAL_PRODUCTION', 		        'YieldType',        'YIELD_PRODUCTION'),
    ('LISBOA_CRUISE_TERMINAL_PRODUCTION', 		        'Amount',           4),
    ('LISBOA_NAVAL_BASE_PRODUCTION', 		            'BuildingType',     'BUILDING_JNR_NAVAL_BASE'),
    ('LISBOA_NAVAL_BASE_PRODUCTION', 		            'YieldType',        'YIELD_PRODUCTION'),
    ('LISBOA_NAVAL_BASE_PRODUCTION', 		            'Amount',           4);

insert or replace into ModifierStrings
    (ModifierId,                                        Context,    Text)
values
    ('LISBOA_FREEPORT_PRODUCTION',                		'Summary',  'LOC_GREATPERSON_JOAQUIM_MARQUES_LISBOA_TIER3_PRODUCTION');

update ModifierStrings set Text = 'LOC_GREATPERSON_JOAQUIM_MARQUES_LISBOA_NAVAL_BASE' where Text = 'LOC_GREATPERSON_JOAQUIM_MARQUES_LISBOA_SEAPORT' and ModifierId = 'GREATPERSON_JOAQUIM_MARQUES_LISBOA_SEAPORT';
update ModifierStrings set Text = 'LOC_GREATPERSON_JOAQUIM_MARQUES_LISBOA_TIER3_HOUSING' where Text = 'LOC_GREATPERSON_JOAQUIM_MARQUES_LISBOA_SEAPORT_HOUSING' and ModifierId = 'GREATPERSON_JOAQUIM_MARQUES_LISBOA_SEAPORT_HOUSING';

insert or replace into Unit_BuildingPrereqs
	(Unit,							PrereqBuilding)
values
	('UNIT_MILITARY_ENGINEER',		'BUILDING_JNR_ENTREPOT');

--------------------------------------------------------------

-- 杂项改动
--------------------------------------------------------------
	-- 神圣之光 博洛尼亚 道观 瑞纳
update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_COMMERCIAL_TIER_1_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_MARKET';
update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_COMMERCIAL_TIER_2_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_BANK';
update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_COMMERCIAL_TIER_3_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_STOCK_EXCHANGE';
	-- 加的夫 荷兰UA
update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_HARBOR_TIER_1_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_LIGHTHOUSE';
update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_HARBOR_TIER_2_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_SHIPYARD';
update Modifiers set SubjectRequirementSetId = 'HD_CITY_HAS_HARBOR_TIER_3_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_SEAPORT';
