UPDATE Buildings SET Name='LOC_BUILDING_GOV_CITYSTATES_NAME' WHERE BuildingType='BUILDING_GOV_CITYSTATES';
UPDATE Buildings SET Name='LOC_BUILDING_GOV_SPIES_NAME' WHERE BuildingType='BUILDING_GOV_SPIES';

INSERT OR IGNORE INTO Types
		(Type,									Kind)
VALUES	('BUILDING_JNR_CONSULATE_SPIES',		'KIND_BUILDING'), --情报局
		('BUILDING_JNR_CONSULATE_CITYSTATES',	'KIND_BUILDING'), --外交部
		('BUILDING_JNR_CHANCERY_SPIES',			'KIND_BUILDING'), --国家安全局
		('BUILDING_JNR_CHANCERY_CITYSTATES',	'KIND_BUILDING'); --国际汇兑处

--情报局间谍+2视野
INSERT OR IGNORE INTO Types
		(Type,											Kind)
VALUES
		('ABILITY_CONSULATE_SPIES_SIGHT',				'KIND_ABILITY');
INSERT OR IGNORE INTO TypeTags
		(Type,											Tag)
VALUES
		('ABILITY_CONSULATE_SPIES_SIGHT',				'CLASS_SPY');
insert or replace into UnitAbilities 
		(UnitAbilityType, 								Name, 											Description, 										Inactive) 
values
		('ABILITY_CONSULATE_SPIES_SIGHT',				'LOC_ABILITY_CONSULATE_SPIES_SIGHT_NAME',		'LOC_ABILITY_CONSULATE_SPIES_SIGHT_DESCRIPTION',	1);
insert or replace into UnitAbilityModifiers
		(UnitAbilityType,								ModifierId)
values
		('ABILITY_CONSULATE_SPIES_SIGHT',				'CONSULATE_SPIES_BONUS_SIGHT');

INSERT OR REPLACE INTO Buildings
		(BuildingType,							PrereqDistrict,					PrereqCivic,					Cost,	Maintenance,	PurchaseYield,	AdvisorType,		Name,											Description)
VALUES	('BUILDING_JNR_CONSULATE_SPIES',		'DISTRICT_DIPLOMATIC_QUARTER',	NULL,	                    	150,	1,				'YIELD_GOLD',	'ADVISOR_GENERIC',	'LOC_BUILDING_JNR_CONSULATE_SPIES_NAME',		'LOC_BUILDING_JNR_CONSULATE_SPIES_DESCRIPTION'),
		('BUILDING_JNR_CONSULATE_CITYSTATES',	'DISTRICT_DIPLOMATIC_QUARTER',	'CIVIC_DEFENSIVE_TACTICS',	    150,	1,				'YIELD_GOLD',	'ADVISOR_GENERIC',	'LOC_BUILDING_JNR_CONSULATE_CITYSTATES_NAME',	'LOC_BUILDING_JNR_CONSULATE_CITYSTATES_DESCRIPTION'),
		('BUILDING_JNR_CHANCERY_SPIES',			'DISTRICT_DIPLOMATIC_QUARTER',	'CIVIC_DIPLOMATIC_SERVICE',		300,	4,				'YIELD_GOLD',	'ADVISOR_GENERIC',	'LOC_BUILDING_JNR_CHANCERY_SPIES_NAME',			'LOC_BUILDING_JNR_CHANCERY_SPIES_DESCRIPTION'),
		('BUILDING_JNR_CHANCERY_CITYSTATES',	'DISTRICT_DIPLOMATIC_QUARTER',	'CIVIC_EXPLORATION',			300,	4,				'YIELD_GOLD',	'ADVISOR_GENERIC',	'LOC_BUILDING_JNR_CHANCERY_CITY_STATES_NAME',	'LOC_BUILDING_JNR_CHANCERY_CITYSTATES_DESCRIPTION');

update Buildings set PrereqTech = 'TECH_MATHEMATICS' where BuildingType = 'BUILDING_JNR_CONSULATE_SPIES';
update Buildings set MaxPlayerInstances = 1 where PrereqDistrict = 'DISTRICT_DIPLOMATIC_QUARTER';

INSERT OR IGNORE INTO BuildingPrereqs
		(Building,										PrereqBuilding)
VALUES	
		('BUILDING_JNR_CHANCERY_SPIES',					'BUILDING_CONSULATE'),
		('BUILDING_JNR_CHANCERY_SPIES',					'BUILDING_JNR_CONSULATE_SPIES'),
		('BUILDING_JNR_CHANCERY_SPIES',					'BUILDING_JNR_CONSULATE_CITYSTATES'),
		('BUILDING_JNR_CHANCERY_CITYSTATES',			'BUILDING_CONSULATE'),
		('BUILDING_JNR_CHANCERY_CITYSTATES',			'BUILDING_JNR_CONSULATE_SPIES'),
		('BUILDING_JNR_CHANCERY_CITYSTATES',			'BUILDING_JNR_CONSULATE_CITYSTATES'),
		('BUILDING_HD_REGIONAL_COUNCIL_CENTER',			'BUILDING_JNR_CHANCERY_SPIES'),
		('BUILDING_HD_REGIONAL_COUNCIL_CENTER',			'BUILDING_JNR_CHANCERY_CITYSTATES'),
		('BUILDING_HD_WORLD_PARLIAMENT_HEADQUARTERS',	'BUILDING_JNR_CHANCERY_CITYSTATES'),
		('BUILDING_HD_WORLD_PARLIAMENT_HEADQUARTERS',	'BUILDING_JNR_CHANCERY_SPIES'),
		('BUILDING_HD_HUMAN_RIGHTS_COUNCIL',			'BUILDING_JNR_CHANCERY_SPIES'),
		('BUILDING_HD_HUMAN_RIGHTS_COUNCIL',			'BUILDING_JNR_CHANCERY_CITYSTATES'),
		('BUILDING_HD_MINISTRY_OF_NATIONAL_DEFENSE',	'BUILDING_JNR_CHANCERY_CITYSTATES'),
		('BUILDING_HD_MINISTRY_OF_NATIONAL_DEFENSE',	'BUILDING_JNR_CHANCERY_SPIES');

INSERT OR IGNORE INTO MutuallyExclusiveBuildings
		(Building,								MutuallyExclusiveBuilding)
VALUES	('BUILDING_CONSULATE',					'BUILDING_JNR_CONSULATE_SPIES'),
		('BUILDING_CONSULATE',					'BUILDING_JNR_CONSULATE_CITYSTATES'),

		('BUILDING_JNR_CONSULATE_SPIES',		'BUILDING_CONSULATE'),
		('BUILDING_JNR_CONSULATE_SPIES',		'BUILDING_JNR_CONSULATE_CITYSTATES'),

		('BUILDING_JNR_CONSULATE_CITYSTATES',	'BUILDING_JNR_CONSULATE_SPIES'),
		('BUILDING_JNR_CONSULATE_CITYSTATES',	'BUILDING_CONSULATE'),

		('BUILDING_CHANCERY',					'BUILDING_JNR_CHANCERY_SPIES'),
		('BUILDING_CHANCERY',					'BUILDING_JNR_CHANCERY_CITYSTATES'),

		('BUILDING_JNR_CHANCERY_SPIES',			'BUILDING_CHANCERY'),
		('BUILDING_JNR_CHANCERY_SPIES',			'BUILDING_JNR_CHANCERY_CITYSTATES'),

		('BUILDING_JNR_CHANCERY_CITYSTATES',	'BUILDING_JNR_CHANCERY_SPIES'),
		('BUILDING_JNR_CHANCERY_CITYSTATES',	'BUILDING_CHANCERY');

insert or replace into BuildingModifiers
    (BuildingType,                  			ModifierId)
values
	--情报局
    ('BUILDING_JNR_CONSULATE_SPIES',         	'CONSULATE_INFLUENCEPOINTS'),
	('BUILDING_JNR_CONSULATE_SPIES',			'GOV_GRANT_SPY'),
	('BUILDING_JNR_CONSULATE_SPIES',			'GOV_ADD_SPY_UNIT'),
	('BUILDING_JNR_CONSULATE_SPIES',			'GOV_INCREASE_SPY_LEVEL'),
	('BUILDING_JNR_CONSULATE_SPIES',         	'DIPLOMATIC_QUARTER_AWARD_ONE_INFLUENCE_TOKEN'),
	('BUILDING_JNR_CONSULATE_SPIES',            'CHANCERY_OFFENSIVESPYTIME'),
	('BUILDING_JNR_CONSULATE_SPIES',         	'SPIES_BONUS_SIGHT_ATTACH'),
    ('BUILDING_JNR_CONSULATE_SPIES',            'CHANCERY_GRANT_SPY_FREE_PROMOTION'),
	('BUILDING_JNR_CONSULATE_SPIES',            'TRAIT_EACH_DIPLO_VISIBILITY_COMBAT_MODIFIER'),
	--外交部
	('BUILDING_JNR_CONSULATE_CITYSTATES',       'CONSULATE_INFLUENCEPOINTS'),
	('BUILDING_JNR_CONSULATE_CITYSTATES',		'BUILDING_GOV_CITYSTATES_UNIT_STRENGTH'),
	('BUILDING_JNR_CONSULATE_CITYSTATES',		'BUILDING_GOV_CITYSTATES_LEVERAGED_UNIT_STRENGTH'),
	('BUILDING_JNR_CONSULATE_CITYSTATES',		'BUILDING_GOV_LEVY_DISCOUNT'),
	('BUILDING_JNR_CONSULATE_CITYSTATES',       'DIPLOMATIC_QUARTER_AWARD_ONE_INFLUENCE_TOKEN'),
	--国家安全局
	('BUILDING_JNR_CHANCERY_SPIES',         	'CHANCERY_INFLUENCEPOINTS'),
	('BUILDING_JNR_CHANCERY_SPIES',         	'DIPLOMATIC_QUARTER_AWARD_ONE_INFLUENCE_TOKEN'),
	('BUILDING_JNR_CHANCERY_SPIES',				'CONSULATE_SPY_BONUS'),
	('BUILDING_JNR_CHANCERY_SPIES',				'CHANCERY_COUNTERYSPY_SCIENCE'),
	('BUILDING_JNR_CHANCERY_SPIES',				'GOV_GRANT_SPY'),
	('BUILDING_JNR_CHANCERY_SPIES',				'GOV_ADD_SPY_UNIT'),
	--国际汇兑处
	('BUILDING_JNR_CHANCERY_CITYSTATES',       	'CHANCERY_INFLUENCEPOINTS'),
	('BUILDING_JNR_CHANCERY_CITYSTATES',        'DIPLOMATIC_QUARTER_AWARD_ONE_INFLUENCE_TOKEN'),
	('BUILDING_JNR_CHANCERY_CITYSTATES',        'CHANCERY_CITYSTATES_DELEGATION_GOLD'),
	-- ('BUILDING_JNR_CHANCERY_CITYSTATES',        'CHANCERY_CITYSTATES_DELEGATION_SCIENCE'),
	-- ('BUILDING_JNR_CHANCERY_CITYSTATES',        'CHANCERY_CITYSTATES_DELEGATION_CULTURE'),
	('BUILDING_JNR_CHANCERY_CITYSTATES',        'CHANCERY_CITYSTATES_EMBASSY_GOLD'),
	-- ('BUILDING_JNR_CHANCERY_CITYSTATES',        'CHANCERY_CITYSTATES_EMBASSY_SCIENCE'),
	-- ('BUILDING_JNR_CHANCERY_CITYSTATES',        'CHANCERY_CITYSTATES_EMBASSY_CULTURE'),
	('BUILDING_JNR_CHANCERY_CITYSTATES',        'MERCHANTCONFEDERATION_INFLUENCETOKENGOLD');

--modifiers
-- Types
--------------------------------------------------------------
INSERT OR IGNORE INTO Types
	(Type,																	Kind)
VALUES
	('MODIFIER_JNR_ALLIANCE_PLAYERS_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD',	'KIND_MODIFIER'),
	('MODIFIER_JNR_EMERGENCY_PLAYERS_GRANT_INFLUENCE_TOKEN',				'KIND_MODIFIER');
--------------------------------------------------------------

-- DynamicModifiers
--------------------------------------------------------------
INSERT OR IGNORE INTO DynamicModifiers
	(ModifierType,															CollectionType,					EffectType)
VALUES
	('MODIFIER_JNR_ALLIANCE_PLAYERS_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD',	'COLLECTION_ALLIANCE_PLAYERS',	'EFFECT_ADJUST_CITY_STATE_TRADE_ROUTE_FLAT_YIELD'),
	('MODIFIER_JNR_EMERGENCY_PLAYERS_GRANT_INFLUENCE_TOKEN',				'COLLECTION_EMERGENCY_PLAYERS',	'EFFECT_GRANT_INFLUENCE_TOKEN');
--------------------------------------------------------------
INSERT OR IGNORE INTO Modifiers
	(ModifierId,									ModifierType,															SubjectStackLimit,	SubjectRequirementSetId)
VALUES	
	--外交部城邦商路产出
	('JNR_CONSULATE_TRADE_CITYSTATES_FOOD',			'MODIFIER_JNR_ALLIANCE_PLAYERS_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD',	NULL,				'PLAYER_HAS_CONSULATE_JNR'),
	('JNR_CONSULATE_TRADE_CITYSTATES_PRODUCTION',	'MODIFIER_JNR_ALLIANCE_PLAYERS_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD',	NULL,				'PLAYER_HAS_CONSULATE_JNR'),
	('JNR_CONSULATE_TRADE_CITYSTATES_GOLD',			'MODIFIER_JNR_ALLIANCE_PLAYERS_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD',	NULL,				'PLAYER_HAS_CONSULATE_JNR'),
	('JNR_CONSULATE_TRADE_CITYSTATES_SCIENCE',		'MODIFIER_JNR_ALLIANCE_PLAYERS_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD',	NULL,				'PLAYER_HAS_CONSULATE_JNR'),
	('JNR_CONSULATE_TRADE_CITYSTATES_CULTURE',		'MODIFIER_JNR_ALLIANCE_PLAYERS_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD',	NULL,				'PLAYER_HAS_CONSULATE_JNR'),
	('JNR_CONSULATE_TRADE_CITYSTATES_FAITH',		'MODIFIER_JNR_ALLIANCE_PLAYERS_ADJUST_TRADE_ROUTES_CITY_STATE_YIELD',	NULL,				'PLAYER_HAS_CONSULATE_JNR'),
	--同盟点数
	('JNR_CONSULATE_ALLIANCE_POINTS',				'MODIFIER_PLAYER_ADJUST_ALLIANCE_POINTS',								NULL,				NULL),
	--外交支持
	('JNR_CHANCERY_ALLIANCE_FAVOR',					'MODIFIER_PLAYER_ADJUST_ALLIANCE_FAVOR_MULTIPLIER',						NULL,				NULL),
	--情报局间谍视野+2
	('SPIES_BONUS_SIGHT_ATTACH',					'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',									NULL,				'UNIT_IS_SPY'),
	('CONSULATE_SPIES_BONUS_SIGHT',					'MODIFIER_PLAYER_UNIT_ADJUST_SIGHT',									NULL,				'PLAYER_HAS_BUILDING_JNR_CONSULATE_SPIES_REQUIREMENTS'),
	--总领馆商路加成
	('CHANCERY_TRADE_ROUTE_SCIENCE_CHANGE',			'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',		NULL,				'CITY_HAS_BUILDING_CHANCERY_REQUIREMENTS'),
	('CHANCERY_TRADE_ROUTE_SCIENCE_CHANGE_MODIFIER',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_ALLY_ROUTE',		NULL,				NULL),
	('CHANCERY_TRADE_ROUTE_CULTURE_CHANGE',			'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',		NULL,				'CITY_HAS_BUILDING_CHANCERY_REQUIREMENTS'),
	('CHANCERY_TRADE_ROUTE_CULTURE_CHANGE_MODIFIER',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_ALLY_ROUTE',		NULL,				NULL),
	--国际汇兑处代表团、大使馆+金瓶琴
	('CHANCERY_CITYSTATES_DELEGATION_GOLD',			'MODIFIER_PLAYER_ADJUST_YIELD_FROM_DELEGATIONS',						NULL,				'PLAYER_HAS_BUILDING_JNR_CHANCERY_CITYSTATES_REQUIREMENTS'),
	-- ('CHANCERY_CITYSTATES_DELEGATION_SCIENCE',		'MODIFIER_PLAYER_ADJUST_YIELD_FROM_DELEGATIONS',						NULL,				'PLAYER_HAS_BUILDING_JNR_CHANCERY_CITYSTATES_REQUIREMENTS'),
	-- ('CHANCERY_CITYSTATES_DELEGATION_CULTURE',		'MODIFIER_PLAYER_ADJUST_YIELD_FROM_DELEGATIONS',						NULL,				'PLAYER_HAS_BUILDING_JNR_CHANCERY_CITYSTATES_REQUIREMENTS'),
	('CHANCERY_CITYSTATES_EMBASSY_GOLD',			'MODIFIER_PLAYER_ADJUST_YIELD_FROM_EMBASSIES',							NULL,				'PLAYER_HAS_BUILDING_JNR_CHANCERY_CITYSTATES_REQUIREMENTS'),
	-- ('CHANCERY_CITYSTATES_EMBASSY_SCIENCE',			'MODIFIER_PLAYER_ADJUST_YIELD_FROM_EMBASSIES',							NULL,				'PLAYER_HAS_BUILDING_JNR_CHANCERY_CITYSTATES_REQUIREMENTS'),
	-- ('CHANCERY_CITYSTATES_EMBASSY_CULTURE',			'MODIFIER_PLAYER_ADJUST_YIELD_FROM_EMBASSIES',							NULL,				'PLAYER_HAS_BUILDING_JNR_CHANCERY_CITYSTATES_REQUIREMENTS'),
	--国际汇兑处每个类型的宗主城邦提供+1贸易路线
	('JNR_CHANCERY_UNIQUE_INFLUENCE_CULTURAL',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',									1,					'PLAYER_IS_SUZERAIN'),
	('JNR_CHANCERY_TRADE_CAPACITY_CULTURAL',		'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',							NULL,				'PLAYER_HAS_CHANCERY_CITYSTATES_JNR'),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_INDUSTRIAL',	'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',									1,					'PLAYER_IS_SUZERAIN'),
	('JNR_CHANCERY_TRADE_CAPACITY_INDUSTRIAL',		'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',							NULL,				'PLAYER_HAS_CHANCERY_CITYSTATES_JNR'),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_MILITARISTIC',	'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',									1,					'PLAYER_IS_SUZERAIN'),
	('JNR_CHANCERY_TRADE_CAPACITY_MILITARISTIC',	'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',							NULL,				'PLAYER_HAS_CHANCERY_CITYSTATES_JNR'),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_RELIGIOUS',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',									1,					'PLAYER_IS_SUZERAIN'),
	('JNR_CHANCERY_TRADE_CAPACITY_RELIGIOUS',		'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',							NULL,				'PLAYER_HAS_CHANCERY_CITYSTATES_JNR'),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_SCIENTIFIC',	'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',									1,					'PLAYER_IS_SUZERAIN'),
	('JNR_CHANCERY_TRADE_CAPACITY_SCIENTIFIC',		'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',							NULL,				'PLAYER_HAS_CHANCERY_CITYSTATES_JNR'),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_TRADE',			'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',									1,					'PLAYER_IS_SUZERAIN'),
	('JNR_CHANCERY_TRADE_CAPACITY_TRADE',			'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',							NULL,				'PLAYER_HAS_CHANCERY_CITYSTATES_JNR'),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_AGRICULTURAL',	'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',									1,					'PLAYER_IS_SUZERAIN'),
	('JNR_CHANCERY_TRADE_CAPACITY_AGRICULTURAL',	'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',							NULL,				'PLAYER_HAS_CHANCERY_CITYSTATES_JNR'),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_CONSULAR',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',									1,					'PLAYER_IS_SUZERAIN'),
	('JNR_CHANCERY_TRADE_CAPACITY_CONSULAR',		'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',							NULL,				'PLAYER_HAS_CHANCERY_CITYSTATES_JNR'),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_ENTERTAINMENT',	'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',									1,					'PLAYER_IS_SUZERAIN'),
	('JNR_CHANCERY_TRADE_CAPACITY_ENTERTAINMENT',	'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',							NULL,				'PLAYER_HAS_CHANCERY_CITYSTATES_JNR'),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_MARITIME',		'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER',									1,					'PLAYER_IS_SUZERAIN'),
	('JNR_CHANCERY_TRADE_CAPACITY_MARITIME',		'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY',							NULL,				'PLAYER_HAS_CHANCERY_CITYSTATES_JNR');
	-- --狄多贸易路线
	-- ('TRADE_ROUTE_CONSULATE_SPIES',					'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_CAPACITY',         			NULL,				'PLAYER_HAS_BUILDING_JNR_CONSULATE_SPIES_REQUIREMENTS'),
	-- ('TRADE_ROUTE_CONSULATE_CITYSTATES',			'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_CAPACITY',					NULL,				'PLAYER_HAS_BUILDING_JNR_CONSULATE_CITYSTATES_REQUIREMENTS'),
	-- ('TRADE_ROUTE_CHANCERY_SPIES',					'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_CAPACITY',					NULL,				'PLAYER_HAS_BUILDING_JNR_CHANCERY_SPIES_REQUIREMENTS'),
	-- ('TRADE_ROUTE_CHANCERY_CITYSTATES',				'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_CAPACITY',					NULL,				'PLAYER_HAS_BUILDING_JNR_CHANCERY_CITYSTATES_REQUIREMENTS');

INSERT OR IGNORE INTO ModifierArguments
	(ModifierId,									Name,			Value)
VALUES
	('JNR_CONSULATE_TRADE_CITYSTATES_FOOD',			'YieldType',	'YIELD_FOOD'),
	('JNR_CONSULATE_TRADE_CITYSTATES_FOOD',			'Amount',		1),
	('JNR_CONSULATE_TRADE_CITYSTATES_PRODUCTION',	'YieldType',	'YIELD_PRODUCTION'),
	('JNR_CONSULATE_TRADE_CITYSTATES_PRODUCTION',	'Amount',		1),
	('JNR_CONSULATE_TRADE_CITYSTATES_GOLD',			'YieldType',	'YIELD_GOLD'),
	('JNR_CONSULATE_TRADE_CITYSTATES_GOLD',			'Amount',		2),
	('JNR_CONSULATE_TRADE_CITYSTATES_SCIENCE',		'YieldType',	'YIELD_SCIENCE'),
	('JNR_CONSULATE_TRADE_CITYSTATES_SCIENCE',		'Amount',		1),
	('JNR_CONSULATE_TRADE_CITYSTATES_CULTURE',		'YieldType',	'YIELD_CULTURE'),
	('JNR_CONSULATE_TRADE_CITYSTATES_CULTURE',		'Amount',		1),
	('JNR_CONSULATE_TRADE_CITYSTATES_FAITH',		'YieldType',	'YIELD_FAITH'),
	('JNR_CONSULATE_TRADE_CITYSTATES_FAITH',		'Amount',		1),
	('JNR_CONSULATE_ALLIANCE_POINTS',				'Amount',		1),
	('JNR_CHANCERY_ALLIANCE_FAVOR',					'Amount',		100),
	('SPIES_BONUS_SIGHT_ATTACH',					'AbilityType',	'ABILITY_CONSULATE_SPIES_SIGHT'),
	('CONSULATE_SPIES_BONUS_SIGHT',					'Amount',		2),
	('CHANCERY_TRADE_ROUTE_SCIENCE_CHANGE',			'ModifierId',		'CHANCERY_TRADE_ROUTE_SCIENCE_CHANGE_MODIFIER'),
	('CHANCERY_TRADE_ROUTE_SCIENCE_CHANGE_MODIFIER',			'Amount',		1),
	('CHANCERY_TRADE_ROUTE_SCIENCE_CHANGE_MODIFIER',			'YieldType',	'YIELD_SCIENCE'),
	('CHANCERY_TRADE_ROUTE_CULTURE_CHANGE',			'ModifierId',		'CHANCERY_TRADE_ROUTE_CULTURE_CHANGE_MODIFIER'),
	('CHANCERY_TRADE_ROUTE_CULTURE_CHANGE_MODIFIER',			'Amount',		1),
	('CHANCERY_TRADE_ROUTE_CULTURE_CHANGE_MODIFIER',			'YieldType',	'YIELD_CULTURE'),
	('JNR_CHANCERY_HOSTILE_EMERGENCY_ENVOY_MEMBER',	'Amount',		1),
	('JNR_CHANCERY_HOSTILE_EMERGENCY_ENVOY_TARGET',	'Amount',		1),
	('JNR_CHANCERY_SCORED_COMPETITION_ENVOY',		'Amount',		1),
	('CHANCERY_CITYSTATES_DELEGATION_GOLD',			'YieldType',	'YIELD_GOLD'),
	('CHANCERY_CITYSTATES_DELEGATION_GOLD',			'Amount',		6),
	-- ('CHANCERY_CITYSTATES_DELEGATION_SCIENCE',		'YieldType',	'YIELD_SCIENCE'),
	-- ('CHANCERY_CITYSTATES_DELEGATION_SCIENCE',		'Amount',		4),
	-- ('CHANCERY_CITYSTATES_DELEGATION_CULTURE',		'YieldType',	'YIELD_CULTURE'),
	-- ('CHANCERY_CITYSTATES_DELEGATION_CULTURE',		'Amount',		4),
	('CHANCERY_CITYSTATES_EMBASSY_GOLD',			'YieldType',	'YIELD_GOLD'),
	('CHANCERY_CITYSTATES_EMBASSY_GOLD',			'Amount',		6),
	-- ('CHANCERY_CITYSTATES_EMBASSY_SCIENCE',			'YieldType',	'YIELD_SCIENCE'),
	-- ('CHANCERY_CITYSTATES_EMBASSY_SCIENCE',			'Amount',		4),
	-- ('CHANCERY_CITYSTATES_EMBASSY_CULTURE',			'YieldType',	'YIELD_CULTURE'),
	-- ('CHANCERY_CITYSTATES_EMBASSY_CULTURE',			'Amount',		4),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_CULTURAL',		'ModifierId',	'JNR_CHANCERY_TRADE_CAPACITY_CULTURAL'),
	('JNR_CHANCERY_TRADE_CAPACITY_CULTURAL',		'Amount',		1),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_INDUSTRIAL',	'ModifierId',	'JNR_CHANCERY_TRADE_CAPACITY_INDUSTRIAL'),
	('JNR_CHANCERY_TRADE_CAPACITY_INDUSTRIAL',		'Amount',		1),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_MILITARISTIC',	'ModifierId',	'JNR_CHANCERY_TRADE_CAPACITY_MILITARISTIC'),
	('JNR_CHANCERY_TRADE_CAPACITY_MILITARISTIC',	'Amount',		1),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_RELIGIOUS',		'ModifierId',	'JNR_CHANCERY_TRADE_CAPACITY_RELIGIOUS'),
	('JNR_CHANCERY_TRADE_CAPACITY_RELIGIOUS',		'Amount',		1),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_SCIENTIFIC',	'ModifierId',	'JNR_CHANCERY_TRADE_CAPACITY_SCIENTIFIC'),
	('JNR_CHANCERY_TRADE_CAPACITY_SCIENTIFIC',		'Amount',		1),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_TRADE',			'ModifierId',	'JNR_CHANCERY_TRADE_CAPACITY_TRADE'),
	('JNR_CHANCERY_TRADE_CAPACITY_TRADE',			'Amount',		1),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_AGRICULTURAL',	'ModifierId',	'JNR_CHANCERY_TRADE_CAPACITY_AGRICULTURAL'),
	('JNR_CHANCERY_TRADE_CAPACITY_AGRICULTURAL',	'Amount',		1),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_CONSULAR',		'ModifierId',	'JNR_CHANCERY_TRADE_CAPACITY_CONSULAR'),
	('JNR_CHANCERY_TRADE_CAPACITY_CONSULAR',		'Amount',		1),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_ENTERTAINMENT',	'ModifierId',	'JNR_CHANCERY_TRADE_CAPACITY_ENTERTAINMENT'),
	('JNR_CHANCERY_TRADE_CAPACITY_ENTERTAINMENT',	'Amount',		1),
	('JNR_CHANCERY_UNIQUE_INFLUENCE_MARITIME',		'ModifierId',	'JNR_CHANCERY_TRADE_CAPACITY_MARITIME'),
	('JNR_CHANCERY_TRADE_CAPACITY_MARITIME',		'Amount',		1);
	-- ('TRADE_ROUTE_CONSULATE_SPIES',					'Amount',		1),
	-- ('TRADE_ROUTE_CONSULATE_CITYSTATES',			'Amount',		1),
	-- ('TRADE_ROUTE_CHANCERY_SPIES',					'Amount',		1),
	-- ('TRADE_ROUTE_CHANCERY_CITYSTATES',				'Amount',		1);

--外交部城邦商路产出
INSERT OR IGNORE INTO AllianceEffects
	(AllianceType,			LevelRequirement,	ModifierId)
VALUES
	('ALLIANCE_MILITARY',	1,					'JNR_CONSULATE_TRADE_CITYSTATES_PRODUCTION'),
	('ALLIANCE_ECONOMIC',	1,					'JNR_CONSULATE_TRADE_CITYSTATES_GOLD'),
	('ALLIANCE_RESEARCH',	1,					'JNR_CONSULATE_TRADE_CITYSTATES_SCIENCE'),
	('ALLIANCE_CULTURAL',	1,					'JNR_CONSULATE_TRADE_CITYSTATES_CULTURE'),
	('ALLIANCE_RELIGIOUS',	1,					'JNR_CONSULATE_TRADE_CITYSTATES_FAITH');
delete from AllianceEffects where AllianceType = 'ALLIANCE_MILITARY' and ModifierId = 'JNR_CONSULATE_TRADE_CITYSTATES_GOLD';

--req
UPDATE Modifiers SET SubjectRequirementSetId ='PLAYER_HAS_BUILDING_JNR_CONSULATE_CITYSTATES_REQUIREMENTS' WHERE SubjectRequirementSetId ='PLAYER_HAS_CONSULATE_JNR';

INSERT OR IGNORE INTO RequirementSets
	(RequirementSetId,															RequirementSetType)
VALUES
	('PLAYER_HAS_CONSULATE_CITYSTATES',											'REQUIREMENTSET_TEST_ALL'),
	('ROUTE_BETWEEN_ALLIES_AND_PLAYER_HAS_CHANCERY',							'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_IS_ALLY_LEVEL_1_AND_HAS_CONSULATE',								'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_IS_ALLY_LEVEL_2_AND_HAS_CONSULATE',								'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_IS_ALLY_LEVEL_3_AND_HAS_CONSULATE',								'REQUIREMENTSET_TEST_ALL');

INSERT OR IGNORE INTO RequirementSetRequirements
	(RequirementSetId,															RequirementId)
VALUES
	('PLAYER_HAS_CONSULATE_CITYSTATES',											'REQUIRES_CITY_HAS_CONSULATE_CITYSTATES'),
	('ROUTE_BETWEEN_ALLIES_AND_PLAYER_HAS_CHANCERY',							'REQUIRES_TRADE_ROUTE_BETWEEN_ALLIES'),
	('ROUTE_BETWEEN_ALLIES_AND_PLAYER_HAS_CHANCERY',							'REQUIRES_PLAYER_HAS_BUILDING_CHANCERY'),
	('PLAYER_IS_ALLY_LEVEL_1_AND_HAS_CONSULATE',								'REQUIRES_PLAYER_IS_ALLY_LEVEL_1'),
	('PLAYER_IS_ALLY_LEVEL_1_AND_HAS_CONSULATE',								'REQUIRES_PLAYER_HAS_BUILDING_CONSULATE'),
	('PLAYER_IS_ALLY_LEVEL_2_AND_HAS_CONSULATE',								'REQUIRES_PLAYER_IS_ALLY_LEVEL_2'),
	('PLAYER_IS_ALLY_LEVEL_2_AND_HAS_CONSULATE',								'REQUIRES_PLAYER_HAS_BUILDING_CONSULATE'),
	('PLAYER_IS_ALLY_LEVEL_3_AND_HAS_CONSULATE',								'REQUIRES_PLAYER_IS_ALLY_LEVEL_3'),
	('PLAYER_IS_ALLY_LEVEL_3_AND_HAS_CONSULATE',								'REQUIRES_PLAYER_HAS_BUILDING_CONSULATE');






