--兵营:调整到炼铁，其余不变，90锤
UPDATE Buildings SET	Cost = 90,		PrereqTech = 'TECH_IRON_WORKING',	PrereqCivic = NULL,		Description = 'LOC_BUILDING_BARRACKS_DESCRIPTION_UC_JNR'			WHERE BuildingType = 'BUILDING_BARRACKS';
--马厩：改为90锤，其余不变
UPDATE Buildings SET	Cost = 90,																	Description = 'LOC_BUILDING_STABLE_DESCRIPTION_UC_JNR'				WHERE BuildingType = 'BUILDING_STABLE';
--蒙古ub下调为90锤
UPDATE Buildings SET	Cost = 90,																	Description = 'LOC_BUILDING_ORDU_DESCRIPTION_UC_JNR'				WHERE BuildingType = 'BUILDING_ORDU';
delete from BuildingModifiers where ModifierID = 'STABLE_ADD_HORSES_PRODUCTION' and BuildingType = 'BUILDING_ORDU';
--皇家学堂：取代兵营马厩，马铁均+2锤。铸铜解锁
UPDATE Buildings SET	Cost = 90,		PrereqTech = 'TECH_BRONZE_WORKING',	PrereqCivic = NULL,		Description = 'LOC_BUILDING_BASILIKOI_PAIDES_DESCRIPTION_UC_JNR'	WHERE BuildingType = 'BUILDING_BASILIKOI_PAIDES';

DELETE FROM BuildingReplaces WHERE CivUniqueBuildingType = 'BUILDING_BASILIKOI_PAIDES';

INSERT OR IGNORE INTO BuildingReplaces
		(CivUniqueBuildingType,			ReplacesBuildingType)
select	'BUILDING_BASILIKOI_PAIDES',	'BUILDING_BARRACKS'
where exists (select BuildingType from Buildings where BuildingType = 'BUILDING_BASILIKOI_PAIDES');
INSERT OR IGNORE INTO BuildingReplaces
		(CivUniqueBuildingType,			ReplacesBuildingType)
select	'BUILDING_BASILIKOI_PAIDES',	'BUILDING_STABLE'
where exists (select BuildingType from Buildings where BuildingType = 'BUILDING_BASILIKOI_PAIDES');

INSERT OR IGNORE INTO BuildingModifiers
		(BuildingType,						ModifierId)
select  'BUILDING_BASILIKOI_PAIDES',		'STABLE_ADD_HORSES_PRODUCTION'
where exists (select BuildingType from Buildings where BuildingType = 'BUILDING_BASILIKOI_PAIDES');
--兵工厂：军工解锁。200锤，移出硝石石油加产，改为本城战略地块+1锤，其余不变
UPDATE Buildings SET	Cost = 200,																	Description = 'LOC_BUILDING_ARMORY_DESCRIPTION_UC_JNR'				WHERE BuildingType = 'BUILDING_ARMORY';
delete from BuildingModifiers where ModifierID = 'ARMORY_ADD_RESOURCE_PRODUCTION' and BuildingType = 'BUILDING_ARMORY';
--军事学院：450锤，移除本体产出，+2住房，建筑本体相邻转锤，移除铝铀加产，其余不变
UPDATE Buildings SET	Cost = 450,			Maintenance = 7,			Housing = 2,				Description = 'LOC_BUILDING_MILITARY_ACADEMY_DESCRIPTION_UC_JNR'	WHERE BuildingType = 'BUILDING_MILITARY_ACADEMY';
delete from BuildingModifiers where ModifierID = 'MILITARY_ACADEMY_ADD_RESOURCE_PRODUCTION' and BuildingType = 'BUILDING_MILITARY_ACADEMY';
delete from Building_YieldChanges where BuildingType = 'BUILDING_MILITARY_ACADEMY' and YieldChange = 4;
insert or replace into Building_YieldDistrictCopies
	(BuildingType,						OldYieldType,					NewYieldType)
values
--军事学院
	('BUILDING_MILITARY_ACADEMY',		'YIELD_PRODUCTION',				'YIELD_PRODUCTION'),
--军事政治处
	('BUILDING_JNR_ARSENAL',			'YIELD_PRODUCTION',				'YIELD_CULTURE'),
--军事研究院
	('BUILDING_JNR_PRISON',				'YIELD_PRODUCTION',				'YIELD_SCIENCE');
--建筑特效
insert or replace into Modifiers
	(ModifierId,									ModifierType,															SubjectRequirementSetId)
values
--边关：本城已改良战略+1锤
	('HD_TARGET_RANGE_ADD_STRATEGIC_PRODUCTION',	'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'PLOT_HAS_STRATEGIC_IMPROVED_REQUIREMENTS'),
	('HD_TARGET_RANGE_INFLUENCE_POINTS',			'MODIFIER_CITY_OWNER_ATTACH_MODIFIER',									'HD_PLAYER_HAS_HORSES_AND_IRON_REQUIREMENTS'),
	('HD_TARGET_RANGE_INFLUENCE_POINTS_MODIFIER',	'MODIFIER_PLAYER_ADJUST_INFLUENCE_POINTS_PER_TURN',						NULL),
--斡耳朵：马+3锤
	('HD_ORDU_ADD_HORSES_PRODUCTION',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'HAS_IMPROVED_HORSES'),
--募兵所：本城训练陆地军事单位+50%生产力，本城已改良战略地块+1锤
	('HD_CAVALIER_ADD_STRATEGIC_PRODUCTION',		'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'PLOT_HAS_STRATEGIC_IMPROVED_REQUIREMENTS'),
	('HD_CAVALIER_ALL_MILITARY_UNITS_PRODUCTION',	'MODIFIER_SINGLE_CITY_ADJUST_MILITARY_UNITS_PRODUCTION',				NULL),
--补给站：本城战略资源地块+2锤+2瓶，每回合送1每种已解锁的战略资源
	('HD_DEPOT_ADD_STRATEGIC_PRODUCTION',			'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'PLOT_HAS_STRATEGIC_IMPROVED_REQUIREMENTS'),
	('HD_DEPOT_ADD_STRATEGIC_SCIENCE',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'PLOT_HAS_STRATEGIC_IMPROVED_REQUIREMENTS'),
	-- ('HD_DEPOT_ADD_ALUMINUM_RESOURCE',				'MODIFIER_CITY_OWNER_ATTACH_MODIFIER',									NULL),
	('HD_DEPOT_ADD_ALUMINUM_RESOURCE_MODIFIER',		'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION',					'PLAYER_CAN_SEE_ALUMINUM'),
	('HD_DEPOT_ADD_COAL_RESOURCE_MODIFIER',			'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION',					'PLAYER_CAN_SEE_COAL'),
	('HD_DEPOT_ADD_HORSES_RESOURCE_MODIFIER',		'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION',					'PLAYER_CAN_SEE_HORSES'),
	('HD_DEPOT_ADD_IRON_RESOURCE_MODIFIER',			'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION',					'PLAYER_CAN_SEE_IRON'),
	('HD_DEPOT_ADD_NITER_RESOURCE_MODIFIER',		'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION',					'PLAYER_CAN_SEE_NITER'),
	('HD_DEPOT_ADD_OIL_RESOURCE_MODIFIER',			'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION',					'PLAYER_CAN_SEE_OIL'),
	('HD_DEPOT_ADD_URANIUM_RESOURCE_MODIFIER',		'MODIFIER_SINGLE_CITY_ADJUST_FREE_RESOURCE_EXTRACTION',					'PLAYER_CAN_SEE_URANIUM'),
--军事学院：本城战略资源地块+1锤
	('HD_MILITARY_ACADEMY_ADD_STRATEGIC_PRODUCTION','MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'PLOT_HAS_STRATEGIC_IMPROVED_REQUIREMENTS'),
--军事政治处：训练1个陆地军事单位额外赠送一个相同的单位；本城战略+1锤
	('HD_ARSENAL_ADD_STRATEGIC_PRODUCTION',			'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',							'PLOT_HAS_STRATEGIC_IMPROVED_REQUIREMENTS'),
	('ARSENAL_EXTRA_UNIT',							'MODIFIER_SINGLE_CITY_ADJUST_EXTRA_UNIT_COPY_TAG',						NULL);

insert or replace into ModifierArguments
	(ModifierId,									Name,						Value)
values
--边关
	('HD_TARGET_RANGE_ADD_STRATEGIC_PRODUCTION',	'YieldType',				'YIELD_PRODUCTION'),
	('HD_TARGET_RANGE_ADD_STRATEGIC_PRODUCTION',	'Amount',					1),
	('HD_TARGET_RANGE_INFLUENCE_POINTS',			'ModifierId',				'HD_TARGET_RANGE_INFLUENCE_POINTS_MODIFIER'),
	('HD_TARGET_RANGE_INFLUENCE_POINTS_MODIFIER',	'Amount',					4),
--斡耳朵
	('HD_ORDU_ADD_HORSES_PRODUCTION',				'YieldType',				'YIELD_PRODUCTION'),
	('HD_ORDU_ADD_HORSES_PRODUCTION',				'Amount',					3),
--募兵所
	('HD_CAVALIER_ADD_STRATEGIC_PRODUCTION',		'YieldType',				'YIELD_PRODUCTION'),
	('HD_CAVALIER_ADD_STRATEGIC_PRODUCTION',		'Amount',					1),
	('HD_CAVALIER_ALL_MILITARY_UNITS_PRODUCTION',	'Amount',					50),
--补给站
	('HD_DEPOT_ADD_STRATEGIC_PRODUCTION',			'YieldType',				'YIELD_PRODUCTION'),
	('HD_DEPOT_ADD_STRATEGIC_PRODUCTION',			'Amount',					2),
	('HD_DEPOT_ADD_STRATEGIC_SCIENCE',				'YieldType',				'YIELD_SCIENCE'),
	('HD_DEPOT_ADD_STRATEGIC_SCIENCE',				'Amount',					2),
	('HD_DEPOT_ADD_ALUMINUM_RESOURCE_MODIFIER',		'ResourceType',				'RESOURCE_ALUMINUM'),
	('HD_DEPOT_ADD_ALUMINUM_RESOURCE_MODIFIER',		'Amount',					1),
	('HD_DEPOT_ADD_COAL_RESOURCE_MODIFIER',			'ResourceType',				'RESOURCE_COAL'),
	('HD_DEPOT_ADD_COAL_RESOURCE_MODIFIER',			'Amount',					1),
	('HD_DEPOT_ADD_HORSES_RESOURCE_MODIFIER',		'ResourceType',				'RESOURCE_HORSES'),
	('HD_DEPOT_ADD_HORSES_RESOURCE_MODIFIER',		'Amount',					1),
	('HD_DEPOT_ADD_IRON_RESOURCE_MODIFIER',			'ResourceType',				'RESOURCE_IRON'),
	('HD_DEPOT_ADD_IRON_RESOURCE_MODIFIER',			'Amount',					1),
	('HD_DEPOT_ADD_NITER_RESOURCE_MODIFIER',		'ResourceType',				'RESOURCE_NITER'),
	('HD_DEPOT_ADD_NITER_RESOURCE_MODIFIER',		'Amount',					1),
	('HD_DEPOT_ADD_OIL_RESOURCE_MODIFIER',			'ResourceType',				'RESOURCE_OIL'),
	('HD_DEPOT_ADD_OIL_RESOURCE_MODIFIER',			'Amount',					1),
	('HD_DEPOT_ADD_URANIUM_RESOURCE_MODIFIER',		'ResourceType',				'RESOURCE_URANIUM'),
	('HD_DEPOT_ADD_URANIUM_RESOURCE_MODIFIER',		'Amount',					1),
--军事学院
	('HD_MILITARY_ACADEMY_ADD_STRATEGIC_PRODUCTION','YieldType',				'YIELD_PRODUCTION'),
	('HD_MILITARY_ACADEMY_ADD_STRATEGIC_PRODUCTION','Amount',					1),
--军事政治处
	('HD_ARSENAL_ADD_STRATEGIC_PRODUCTION',			'YieldType',				'YIELD_PRODUCTION'),
	('HD_ARSENAL_ADD_STRATEGIC_PRODUCTION',			'Amount',					1),
	('ARSENAL_EXTRA_UNIT',							'Tag',						'CLASS_LAND_MILITARY'),
	('ARSENAL_EXTRA_UNIT',							'Amount',					1);



insert or replace into BuildingModifiers
	(BuildingType,						ModifierId)
values
--边关
	('BUILDING_JNR_TARGET_RANGE',		'HD_TARGET_RANGE_ADD_STRATEGIC_PRODUCTION'),
	('BUILDING_JNR_TARGET_RANGE',		'HD_TARGET_RANGE_INFLUENCE_POINTS'),
--斡耳朵
	('BUILDING_ORDU',					'HD_ORDU_ADD_HORSES_PRODUCTION'),
--募兵所
	('BUILDING_JNR_CAVALIER',			'HD_CAVALIER_ADD_STRATEGIC_PRODUCTION'),
	('BUILDING_JNR_CAVALIER',			'HD_CAVALIER_ALL_MILITARY_UNITS_PRODUCTION'),
--兵工厂
	('BUILDING_ARMORY',					'HD_CAVALIER_ADD_STRATEGIC_PRODUCTION'),
--补给站
	('BUILDING_JNR_DEPOT',				'HD_DEPOT_ADD_STRATEGIC_PRODUCTION'),
	('BUILDING_JNR_DEPOT',				'HD_DEPOT_ADD_STRATEGIC_SCIENCE'),
	('BUILDING_JNR_DEPOT',				'HD_DEPOT_ADD_ALUMINUM_RESOURCE_MODIFIER'),
	('BUILDING_JNR_DEPOT',				'HD_DEPOT_ADD_COAL_RESOURCE_MODIFIER'),
	('BUILDING_JNR_DEPOT',				'HD_DEPOT_ADD_HORSES_RESOURCE_MODIFIER'),
	('BUILDING_JNR_DEPOT',				'HD_DEPOT_ADD_IRON_RESOURCE_MODIFIER'),
	('BUILDING_JNR_DEPOT',				'HD_DEPOT_ADD_NITER_RESOURCE_MODIFIER'),
	('BUILDING_JNR_DEPOT',				'HD_DEPOT_ADD_OIL_RESOURCE_MODIFIER'),
	('BUILDING_JNR_DEPOT',				'HD_DEPOT_ADD_URANIUM_RESOURCE_MODIFIER'),
--军事学院
	('BUILDING_MILITARY_ACADEMY',		'HD_MILITARY_ACADEMY_ADD_STRATEGIC_PRODUCTION'),
--军事政治处
	('BUILDING_JNR_ARSENAL',			'HD_ARSENAL_ADD_STRATEGIC_PRODUCTION'),
	('BUILDING_JNR_ARSENAL',			'ARSENAL_EXTRA_UNIT'),
--军事研究院
	('BUILDING_JNR_PRISON',				'HD_ARSENAL_ADD_STRATEGIC_PRODUCTION'),
--尼航战士
	('BUILDING_ORDU',					'LAHORE_NIHANG_BARRACKS_ADD_PURCHASE_COST'),
	('BUILDING_JNR_TARGET_RANGE',		'LAHORE_NIHANG_BARRACKS_ADD_PURCHASE_COST'),
	('BUILDING_JNR_DEPOT',				'LAHORE_NIHANG_ARMORY_ADD_PURCHASE_COST'),
	('BUILDING_JNR_CAVALIER',			'LAHORE_NIHANG_ARMORY_ADD_PURCHASE_COST'),
	('BUILDING_JNR_ARSENAL',			'LAHORE_NIHANG_ACADEMY_ADD_PURCHASE_COST'),
	('BUILDING_JNR_PRISON',				'LAHORE_NIHANG_ACADEMY_ADD_PURCHASE_COST'),
	('BUILDING_ORDU',					'LAHORE_NIHANG_BARRACKS_ABILITY'),
	('BUILDING_JNR_TARGET_RANGE',		'LAHORE_NIHANG_BARRACKS_ABILITY'),
	('BUILDING_JNR_DEPOT',				'LAHORE_NIHANG_ARMORY_ABILITY'),
	('BUILDING_JNR_CAVALIER',			'LAHORE_NIHANG_ARMORY_ABILITY'),
	('BUILDING_JNR_ARSENAL',			'LAHORE_NIHANG_ACADEMY_ABILITY'),
	('BUILDING_JNR_PRISON',				'LAHORE_NIHANG_ACADEMY_ABILITY');
delete from BuildingModifiers where
(	ModifierId = 'LAHORE_NIHANG_BARRACKS_ADD_PURCHASE_COST' or ModifierId = 'LAHORE_NIHANG_ARMORY_ADD_PURCHASE_COST' or ModifierId = 'LAHORE_NIHANG_ACADEMY_ADD_PURCHASE_COST'
or 	ModifierId = 'LAHORE_NIHANG_BARRACKS_ABILITY' or ModifierId = 'LAHORE_NIHANG_ARMORY_ABILITY' or ModifierId = 'LAHORE_NIHANG_ACADEMY_ABILITY')
and not exists (select TraitType from TraitModifiers where TraitType = 'MINOR_CIV_LAHORE_NIHANG_TRAIT');

insert or replace into BuildingModifiers
	(BuildingType,						ModifierId)
select
	'BUILDING_JNR_PRISON',				'PRISON_HAS_'||ResourceType||'_BONUS_CAMPUS'
from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
    'PRISON_HAS_'||ResourceType||'_BONUS_CAMPUS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',  'HD_CITY_HAS_IMPROVED_' || ResourceType || '_REQUIREMENTS',  'HD_DISTRICT_IS_DISTRICT_CAMPUS_ADJACENT'
from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

insert or replace into ModifierArguments (ModifierId, Name, Value) select
    'PRISON_HAS_'||ResourceType||'_BONUS_CAMPUS', 'YieldType',  'YIELD_SCIENCE'
from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

insert or replace into ModifierArguments (ModifierId, Name, Value) select
    'PRISON_HAS_'||ResourceType||'_BONUS_CAMPUS', 'Amount',  25
from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

insert or replace into BuildingModifiers
	(BuildingType,						ModifierId)
select
	'BUILDING_JNR_PRISON',				'PRISON_HAS_'||ResourceType||'_BONUS_ENCAMPMENT'
from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
    'PRISON_HAS_'||ResourceType||'_BONUS_ENCAMPMENT', 'MODIFIER_CITY_DISTRICTS_ADJUST_YIELD_MODIFIER',  'HD_CITY_HAS_IMPROVED_' || ResourceType || '_REQUIREMENTS',  'DISTRICT_IS_ENCAMPMENT'
from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

insert or replace into ModifierArguments (ModifierId, Name, Value) select
    'PRISON_HAS_'||ResourceType||'_BONUS_ENCAMPMENT', 'YieldType',  'YIELD_PRODUCTION'
from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

insert or replace into ModifierArguments (ModifierId, Name, Value) select
    'PRISON_HAS_'||ResourceType||'_BONUS_ENCAMPMENT', 'Amount',  50
from Resources where ResourceClassType = 'RESOURCECLASS_STRATEGIC';

--专家产出
insert or replace into Building_CitizenYieldChanges
    (BuildingType,                  YieldType,          YieldChange)
values
--边关
	('BUILDING_JNR_TARGET_RANGE',	'YIELD_PRODUCTION',	1),
	('BUILDING_JNR_TARGET_RANGE',	'YIELD_GOLD',		-1),
--募兵所
	('BUILDING_JNR_CAVALIER',		'YIELD_PRODUCTION',	1),
	('BUILDING_JNR_CAVALIER',		'YIELD_GOLD',		-1),
--补给站
	('BUILDING_JNR_DEPOT',			'YIELD_PRODUCTION',	1),
	('BUILDING_JNR_DEPOT',			'YIELD_GOLD',		-1),
--军事政治处
	('BUILDING_JNR_ARSENAL',		'YIELD_PRODUCTION',	1),
	('BUILDING_JNR_ARSENAL',		'YIELD_CULTURE',	1),
	('BUILDING_JNR_ARSENAL',		'YIELD_GOLD',		-2),
--军事研究院
	('BUILDING_JNR_PRISON',			'YIELD_PRODUCTION',	1),
	('BUILDING_JNR_PRISON',			'YIELD_SCIENCE',	1),
	('BUILDING_JNR_PRISON',			'YIELD_GOLD',		-2);
--政策卡适配
--加速卡
update Modifiers set SubjectRequirementSetId = 'CITY_HAS_DISTRICT_ENCAMPMENT_TIER_1_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_BARRACKS_STABLE_MILITARITIC_CITY_STATE' and ModifierType = 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION';
update Modifiers set SubjectRequirementSetId = 'CITY_HAS_DISTRICT_ENCAMPMENT_TIER_2_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_ARMORY' and ModifierType = 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION';
update Modifiers set SubjectRequirementSetId = 'CITY_HAS_DISTRICT_ENCAMPMENT_TIER_3_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_MILITARY_ACADEMY' and ModifierType = 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION';
-- --军事研究
-- insert or replace into PolicyModifiers
-- 	(PolicyType,					ModifierId)
-- values
-- 	('POLICY_MILITARY_RESEARCH',	'MILITARYRESEARCH_ARSENAL_SCIENCE_MODIFIER'),
-- 	('POLICY_MILITARY_RESEARCH',	'MILITARYRESEARCH_PRISON_SCIENCE_MODIFIER');
--军事组织
-- update Modifiers set SubjectRequirementSetId = 'CITY_HAS_DISTRICT_ENCAMPMENT_TIER_2_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_ARMORY' and ModifierId = 'MILITARYORGANIZATION_GREATGENERAL_ARMORY';
-- update Modifiers set SubjectRequirementSetId = 'CITY_HAS_DISTRICT_ENCAMPMENT_TIER_3_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_MILITARY_ACADEMY' and ModifierId = 'MILITARYORGANIZATION_GREATGENERAL_MILITARYACADEMY';
-- insert or replace into Modifiers
-- 	(ModifierId,												ModifierType)
-- values
-- 	('MILITARYRESEARCH_ARSENAL_SCIENCE_MODIFIER',				'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
-- 	('MILITARYRESEARCH_PRISON_SCIENCE_MODIFIER',				'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE');

-- insert or replace into ModifierArguments
-- 	(ModifierId,												Name,					Value)
-- values
-- 	('MILITARYRESEARCH_ARSENAL_SCIENCE_MODIFIER',			'BuildingType',			'BUILDING_JNR_ARSENAL'),
-- 	('MILITARYRESEARCH_ARSENAL_SCIENCE_MODIFIER',			'YieldType',			'YIELD_SCIENCE'),
-- 	('MILITARYRESEARCH_ARSENAL_SCIENCE_MODIFIER',			'Amount',				5),
-- 	('MILITARYRESEARCH_PRISON_SCIENCE_MODIFIER',			'BuildingType',			'BUILDING_JNR_PRISON'),
-- 	('MILITARYRESEARCH_PRISON_SCIENCE_MODIFIER',			'YieldType',			'YIELD_SCIENCE'),
-- 	('MILITARYRESEARCH_PRISON_SCIENCE_MODIFIER',			'Amount',				5);


--新增条件
insert or ignore into RequirementSets
	(RequirementSetId,												RequirementSetType)
values
	-- ('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_1_BUILDING_REQUIREMENTS',		    'REQUIREMENTSET_TEST_ANY'),
	-- ('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_2_BUILDING_REQUIREMENTS',		    'REQUIREMENTSET_TEST_ANY'),
  -- ('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_3_BUILDING_REQUIREMENTS',		    'REQUIREMENTSET_TEST_ANY'),
	('PLAYER_HAS_CAVALIER_JNR',										'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_HAS_DEPOT_JNR',										'REQUIREMENTSET_TEST_ALL');
--	('CITY_HAS_BUILDING_CITY_POLICY_JIMI_AND_HORSES_IRON',			'REQUIREMENTSET_TEST_ALL');

insert or ignore into RequirementSetRequirements	
	(RequirementSetId,													RequirementId)
values
	('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_1_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_BARRACKS'),
  ('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_1_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_STABLE'),
	('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_1_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_TARGET_RANGE'),
	('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_2_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_ARMORY'),
	('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_2_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_CAVALIER'),
	('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_2_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_DEPOT'),
	('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_3_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_MILITARY_ACADEMY'),
	('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_3_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_ARSENAL'),
	('CITY_HAS_DISTRICT_ENCAMPMENT_TIER_3_BUILDING_REQUIREMENTS',      		'REQUIRES_CITY_HAS_BUILDING_JNR_PRISON'),
--火药
	('PLAYER_HAS_CAVALIER_JNR',											'REQUIRES_PLAYER_HAS_CAVALIER_JNR'),
	('PLAYER_HAS_DEPOT_JNR',											'REQUIRES_PLAYER_HAS_DEPOT_JNR'),
--边关
--	('CITY_HAS_BUILDING_CITY_POLICY_JIMI_AND_HORSES_IRON',				'REQUIRES_PLAYER_HAS_ENOUGH_IRON'),
--	('CITY_HAS_BUILDING_CITY_POLICY_JIMI_AND_HORSES_IRON',				'REQUIRES_PLAYER_HAS_ENOUGH_HORSES'),
--	('CITY_HAS_BUILDING_CITY_POLICY_JIMI_AND_HORSES_IRON',				'REQUIRES_CITY_HAS_BUILDING_CITY_POLICY_JIMI'),
--一体化空间	
	('CITY_HAS_MILITARY_ACADEMY_OR_SEAPORT',							'REQUIRES_CITY_HAS_BUILDING_JNR_ARSENAL'),
	('CITY_HAS_MILITARY_ACADEMY_OR_SEAPORT',							'REQUIRES_CITY_HAS_BUILDING_JNR_PRISON');

insert or ignore into Requirements
	(RequirementId,										RequirementType)
values
	('REQUIRES_PLAYER_HAS_CAVALIER_JNR',				'REQUIREMENT_PLAYER_HAS_BUILDING'),
	('REQUIRES_PLAYER_HAS_DEPOT_JNR',					'REQUIREMENT_PLAYER_HAS_BUILDING');
insert or ignore into RequirementArguments
	(RequirementId,										Name,				Value)
values
	('REQUIRES_PLAYER_HAS_CAVALIER_JNR',				'BuildingType',		'BUILDING_JNR_CAVALIER'),
	('REQUIRES_PLAYER_HAS_DEPOT_JNR',					'BuildingType',		'BUILDING_JNR_DEPOT');


--ulk适配：火药
update Boosts set TriggerDescription = 'LOC_BOOST_TRIGGER_GUNPOWDER_HD' where TechnologyType = 'TECH_GUNPOWDER';
insert or replace into Modifiers
	(ModifierId,                                    ModifierType,                                           SubjectRequirementSetId,		Permanent,  RunOnce)
values
	('GUNPOWDER_TECHBOOST_CAVALIER_JNR',			'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_CAVALIER_JNR',		1,			1),
	('GUNPOWDER_TECHBOOST_DEPOT_JNR',				'MODIFIER_PLAYER_GRANT_SPECIFIC_TECH_BOOST',			'PLAYER_HAS_DEPOT_JNR',			1,			1);
insert or replace into ModifierArguments
	(ModifierId,									Name,				Value)
values
	('GUNPOWDER_TECHBOOST_CAVALIER_JNR',			'TechType',			'TECH_GUNPOWDER'),
	('GUNPOWDER_TECHBOOST_DEPOT_JNR',				'TechType',			'TECH_GUNPOWDER');
insert or replace into TraitModifiers
	(TraitType,                 ModifierId)
values
	('TRAIT_LEADER_MAJOR_CIV',	'GUNPOWDER_TECHBOOST_CAVALIER_JNR'),
	('TRAIT_LEADER_MAJOR_CIV',	'GUNPOWDER_TECHBOOST_DEPOT_JNR');


--Ibrahim
update Modifiers set SubjectRequirementSetId = 'CITY_HAS_DISTRICT_ENCAMPMENT_TIER_1_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_BARRACKS_STABLE_MILITARITIC_CITY_STATE' and ModifierID = 'HEAD_FALCONER_BARRACKS_STABLE_SCIENCE_BONUS1';
update Modifiers set SubjectRequirementSetId = 'CITY_HAS_DISTRICT_ENCAMPMENT_TIER_2_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_ARMORY' and ModifierID = 'HEAD_FALCONER_ARMORY_SCIENCE_BONUS1';
update Modifiers set SubjectRequirementSetId = 'CITY_HAS_DISTRICT_ENCAMPMENT_TIER_3_BUILDING_REQUIREMENTS' where SubjectRequirementSetId = 'BUILDING_IS_MILITARY_ACADEMY' and ModifierID = 'HEAD_FALCONER_MILITARY_ACADEMY_SCIENCE_BONUS1';

--伟人点
INSERT OR IGNORE INTO Building_GreatPersonPoints
		(BuildingType,					GreatPersonClassType,			PointsPerTurn)
VALUES	
--边关
		('BUILDING_JNR_TARGET_RANGE',	'GREAT_PERSON_CLASS_GENERAL',	2),
--募兵所		
		('BUILDING_JNR_CAVALIER',		'GREAT_PERSON_CLASS_GENERAL',	2),
--补给站
		('BUILDING_JNR_DEPOT',			'GREAT_PERSON_CLASS_GENERAL',	2),
--军事政治处
		('BUILDING_JNR_ARSENAL',		'GREAT_PERSON_CLASS_GENERAL',	2),
--军事研究院
		('BUILDING_JNR_PRISON',			'GREAT_PERSON_CLASS_GENERAL',	2);
--军工
insert or replace into Unit_BuildingPrereqs
	(Unit,							PrereqBuilding)
values
	('UNIT_MILITARY_ENGINEER',		'BUILDING_JNR_CAVALIER'),
	('UNIT_MILITARY_ENGINEER',		'BUILDING_JNR_DEPOT');

-- 铜雀台
insert or replace into BuildingPrereqs (Building, PrereqBuilding)
	select 'BUILDING_PHANTA_BRONZE_BIRD_TERRACE', 'BUILDING_JNR_TARGET_RANGE'
where exists (select BuildingType from Buildings where BuildingType = 'BUILDING_PHANTA_BRONZE_BIRD_TERRACE');