-- UC_NBH_Buildings
-- Author: JNR
--------------------------------------------------------------

-- Types
--------------------------------------------------------------
INSERT OR IGNORE INTO Types
		(Type,								Kind)
VALUES	('BUILDING_JNR_TRANSIT_HUB',		'KIND_BUILDING'),
		('BUILDING_JNR_RECYCLING_PLANT',	'KIND_BUILDING'),
		('BUILDING_JNR_HOSPITAL',			'KIND_BUILDING'),
		('BUILDING_JNR_ART_GALLERY',		'KIND_BUILDING'),
		('BUILDING_JNR_MEDITATION',			'KIND_BUILDING');
--------------------------------------------------------------

-- Buildings
--------------------------------------------------------------
insert or ignore into Buildings
		(BuildingType,						PrereqDistrict,				PrereqTech,						PrereqCivic,			Cost,	Maintenance,	CitizenSlots,	Housing,	Entertainment,		RegionalRange,		PurchaseYield,	AdvisorType,			Name,										Description)
VALUES	('BUILDING_JNR_TRANSIT_HUB',		'DISTRICT_NEIGHBORHOOD',	'TECH_CIVIL_ENGINEERING_HD',	NULL,					400,	7,				2,				0,			0,					0,					'YIELD_GOLD',	'ADVISOR_GENERIC',		'LOC_BUILDING_JNR_TRANSIT_HUB_NAME',		'LOC_BUILDING_JNR_TRANSIT_HUB_DESCRIPTION'),
		('BUILDING_JNR_RECYCLING_PLANT',	'DISTRICT_NEIGHBORHOOD',	NULL,				'CIVIC_URBANIZATION',					400,	7,				2,				0,			1,					0,					'YIELD_GOLD',	'ADVISOR_GENERIC',		'LOC_BUILDING_JNR_RECYCLING_PLANT_NAME',	'LOC_BUILDING_JNR_RECYCLING_PLANT_DESCRIPTION'),
		('BUILDING_JNR_HOSPITAL',			'DISTRICT_NEIGHBORHOOD',	'TECH_SANITATION',				NULL,					400,	7,				2,				2,			0,					0,					'YIELD_GOLD',	'ADVISOR_TECHNOLOGY',	'LOC_BUILDING_JNR_HOSPITAL_NAME',			'LOC_BUILDING_JNR_HOSPITAL_DESCRIPTION'),
		('BUILDING_JNR_ART_GALLERY',		'DISTRICT_NEIGHBORHOOD',	'TECH_RADIO',					NULL,					360,	7,				2,				0,			0,					0,					'YIELD_GOLD',	'ADVISOR_CULTURE',		'LOC_BUILDING_JNR_ART_GALLERY_NAME',		'LOC_BUILDING_JNR_ART_GALLERY_DESCRIPTION'),
		('BUILDING_JNR_MEDITATION',			'DISTRICT_NEIGHBORHOOD',	NULL,							'CIVIC_URBAN_DESIGN_HD',		360,	7,				2,				2,			0,					0,					'YIELD_GOLD',	'ADVISOR_CULTURE',		'LOC_BUILDING_JNR_MEDITATION_NAME',			'LOC_BUILDING_JNR_MEDITATION_DESCRIPTION');
--------------------------------------------------------------

-- Buildings_XP2
--------------------------------------------------------------
INSERT OR IGNORE INTO Buildings_XP2
		(BuildingType,						RequiredPower,		EntertainmentBonusWithPower)
VALUES	('BUILDING_JNR_TRANSIT_HUB',		2,					0),
		('BUILDING_JNR_RECYCLING_PLANT',	4,					0),
		('BUILDING_JNR_HOSPITAL',			4,					0),
		('BUILDING_JNR_ART_GALLERY',		4,					0),
		('BUILDING_JNR_MEDITATION',			4,					0);
--------------------------------------------------------------

-- BuildingPrereqs
--------------------------------------------------------------
INSERT OR IGNORE INTO BuildingPrereqs
		(Building,							PrereqBuilding)
VALUES
		('BUILDING_JNR_TRANSIT_HUB',	'BUILDING_HD_ANCESTRAL_TEMPLE'),
		('BUILDING_JNR_RECYCLING_PLANT',	'BUILDING_HD_ANCESTRAL_TEMPLE'),
		('BUILDING_JNR_HOSPITAL',			'BUILDING_HD_ANCESTRAL_TEMPLE'),
		('BUILDING_JNR_ART_GALLERY',		'BUILDING_HD_ANCESTRAL_TEMPLE'),
		('BUILDING_JNR_MEDITATION',			'BUILDING_HD_ANCESTRAL_TEMPLE'),

		('BUILDING_JNR_TRANSIT_HUB',	'BUILDING_HD_TAVERN'),
		('BUILDING_JNR_RECYCLING_PLANT',	'BUILDING_HD_TAVERN'),
		('BUILDING_JNR_HOSPITAL',			'BUILDING_HD_TAVERN'),
		('BUILDING_JNR_ART_GALLERY',		'BUILDING_HD_TAVERN'),
		('BUILDING_JNR_MEDITATION',			'BUILDING_HD_TAVERN'),

		('BUILDING_JNR_TRANSIT_HUB',	'BUILDING_HD_INN'),
		('BUILDING_JNR_RECYCLING_PLANT',	'BUILDING_HD_INN'),
		('BUILDING_JNR_HOSPITAL',			'BUILDING_HD_INN'),
		('BUILDING_JNR_ART_GALLERY',		'BUILDING_HD_INN'),
		('BUILDING_JNR_MEDITATION',			'BUILDING_HD_INN'),

		('BUILDING_JNR_TRANSIT_HUB',	'BUILDING_HD_DRAMA_STAGE'),
		('BUILDING_JNR_RECYCLING_PLANT',	'BUILDING_HD_DRAMA_STAGE'),
		('BUILDING_JNR_HOSPITAL',			'BUILDING_HD_DRAMA_STAGE'),
		('BUILDING_JNR_ART_GALLERY',		'BUILDING_HD_DRAMA_STAGE'),
		('BUILDING_JNR_MEDITATION',			'BUILDING_HD_DRAMA_STAGE'),

		('BUILDING_JNR_TRANSIT_HUB',	'BUILDING_HD_LOCAL_POLICE_STATION'),
		('BUILDING_JNR_RECYCLING_PLANT',	'BUILDING_HD_LOCAL_POLICE_STATION'),
		('BUILDING_JNR_HOSPITAL',			'BUILDING_HD_LOCAL_POLICE_STATION'),
		('BUILDING_JNR_ART_GALLERY',		'BUILDING_HD_LOCAL_POLICE_STATION'),
		('BUILDING_JNR_MEDITATION',			'BUILDING_HD_LOCAL_POLICE_STATION');
--------------------------------------------------------------

-- MutuallyExclusiveBuildings
--------------------------------------------------------------
DELETE FROM MutuallyExclusiveBuildings WHERE Building='BUILDING_FOOD_MARKET';
DELETE FROM MutuallyExclusiveBuildings WHERE Building='BUILDING_SHOPPING_MALL';

INSERT OR IGNORE INTO MutuallyExclusiveBuildings
		(Building,							MutuallyExclusiveBuilding)
VALUES	('BUILDING_FOOD_MARKET',			'BUILDING_SHOPPING_MALL'),
		('BUILDING_SHOPPING_MALL',			'BUILDING_FOOD_MARKET'),
		('BUILDING_JNR_RECYCLING_PLANT',	'BUILDING_JNR_HOSPITAL'),
		('BUILDING_JNR_HOSPITAL',			'BUILDING_JNR_RECYCLING_PLANT'),
		('BUILDING_JNR_ART_GALLERY',		'BUILDING_JNR_MEDITATION'),
		('BUILDING_JNR_MEDITATION',			'BUILDING_JNR_ART_GALLERY'),
		('BUILDING_JNR_TRANSIT_HUB',			'BUILDING_HD_BUS_STOP'),
		('BUILDING_HD_BUS_STOP',			'BUILDING_JNR_TRANSIT_HUB');
--------------------------------------------------------------